/**
 * ConfigureSubcategorySheet — single source of truth for everything about a subcategory.
 *
 * Replaces:
 *   - EditSubcategoryDialog (identity)
 *   - SubcategorySetupSheet (domain axis + areas + matrix)
 *
 * Layout: vertical sections inside one sheet, each with a short "why this matters"
 * caption. Areas live behind a dedicated dialog — they were too noisy inline.
 */

import { useEffect, useMemo, useRef, useState } from 'react';
import {
  Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription,
} from '@/components/ui/sheet';
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { ScrollArea } from '@/components/ui/scroll-area';
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue,
} from '@/components/ui/select';
import {
  Collapsible, CollapsibleContent, CollapsibleTrigger,
} from '@/components/ui/collapsible';
import {
  Popover, PopoverContent, PopoverTrigger,
} from '@/components/ui/popover';
import { Textarea } from '@/components/ui/textarea';
import { ZoneMapSelector } from '@/components/shared/ZoneMapSelector';
import {
  Settings2, Tag, ListTree, Ruler, Grid3X3, MapPin, Sparkles,
  Plus, Trash2, X, Loader2, Check, ChevronDown, Info, AlertTriangle, Pencil,
} from 'lucide-react';
import { toast } from 'sonner';
import { supabase } from '@/integrations/supabase/client';
import { useQueryClient } from '@tanstack/react-query';
import { useAuth } from '@/contexts/AuthContext';
import {
  useSubcategoryAreas, useSaveSubcategoryAreas,
} from '@/hooks/useSubcategoryAreas';
import {
  autoGenerateDomains, checkDomainImplications, useSupplyDomainsBySubcategory,
} from '@/hooks/useSupplyDomains';
import type { SpecDefinition } from './SpecFilterBar';

const AREA_COLORS = ['#f59e0b', '#3b82f6', '#10b981', '#ef4444', '#8b5cf6', '#ec4899', '#06b6d4', '#84cc16'];

// ─── Variant definition shape (lives in material_subcategories.variant_definitions JSON) ───
interface VariantDef {
  key: string;
  label_en: string;
  label_ar?: string | null;
  options?: (string | number)[];
}

interface AreaDraft {
  id?: string;
  name: string;
  zone_codes: string[];
  color: string;
}

interface Props {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  subcategoryId: string;
  initial: {
    name_en: string;
    name_ar?: string | null;
    spec_definitions: SpecDefinition[];
    variant_definitions: VariantDef | null;
    domain_axis: string | null;
  };
}

// ─── helper: derive variant unit (mirrors composeMaterialName/DB) ───
function deriveUnit(label: string | null | undefined, key: string | null | undefined): string {
  const m = label?.match(/\(([^)]+)\)/);
  if (m && m[1].trim()) return m[1].trim();
  if (key && key.includes('_')) {
    const tail = key.split('_').pop();
    if (tail && tail !== key) return tail;
  }
  return '';
}

// ─── Helper: Translate database errors into user-friendly messages ───
function getFriendlyErrorMessage(error: any): string {
  const message = error?.message || error?.error_description || error?.details || error?.hint || '';
  
  // Foreign key violation - supply_domains linked to orders
  if (message.includes('violates foreign key constraint') && 
      message.includes('fk_orders_domain') &&
      message.includes('supply_domains')) {
    return 'Cannot update or delete supply domains because they are linked to existing orders. Please reassign or complete those orders first.';
  }
  
  // General foreign key violation
  if (message.includes('violates foreign key constraint')) {
    return 'Cannot complete this action because other records are still linked to this data.';
  }
  
  // Unique constraint violation
  if (message.includes('duplicate key') || message.includes('unique constraint')) {
    return 'This value already exists. Please use a different name or value.';
  }
  
  // Not null violation
  if (message.includes('null value in column')) {
    return 'Please fill in all required fields before saving.';
  }
  
  // Fallback: cleaner version of original error
  if (typeof error === 'string') return error;
  
  return 'Something went wrong while saving. Please try again or check your input.';
}

// ─── Helper: extract spec labels from specs
function extractSpecLabels(specs: Record<string, string>, specDefinitions: SpecDefinition[]): string[] {
  const labels: string[] = [];
  for (const spec of specDefinitions) {
    const value = specs[spec.key];
    if (value) {
      const option = spec.options?.find(opt => opt.value === value);
      labels.push(option?.label_en || value);
    }
  }
  return labels;
}

// ─── Helper: build material name
function buildMaterialName(subcategoryName: string, specLabels: string[], variantLabel: string): string {
  const parts = [subcategoryName];
  if (specLabels.length > 0) parts.push(specLabels.join(', '));
  if (variantLabel) parts.push(variantLabel);
  return parts.join(': ');
}

// ─── Sub-component: Identity ───
function IdentitySection({
  nameEn, nameAr, onChange, nameConflict, conflictMessage,
}: {
  nameEn: string; nameAr: string;
  onChange: (patch: { name_en?: string; name_ar?: string }) => void;
  nameConflict?: boolean;
  conflictMessage?: string;
}) {
  return (
    <SectionCard
      icon={<Tag className="h-4 w-4" />}
      title="Identity"
      caption="The display name shown everywhere — registry, quotes, PDFs. Arabic is used in supplier-facing communication."
    >
      <div className="grid grid-cols-2 gap-3">
        <div className="space-y-1">
          <Label className="text-xs">English name *</Label>
          <Input
            value={nameEn}
            onChange={e => onChange({ name_en: e.target.value })}
            placeholder="e.g. Cement Block"
            className={`h-9 ${nameConflict ? 'border-red-500 focus-visible:ring-red-500' : ''}`}
          />
          {nameConflict && (
            <p className="text-[10px] text-red-500">{conflictMessage || 'This name is already used by another subcategory'}</p>
          )}
        </div>
        <div className="space-y-1">
          <Label className="text-xs">Arabic name</Label>
          <Input
            value={nameAr}
            onChange={e => onChange({ name_ar: e.target.value })}
            placeholder="مثال: بلوك إسمنتي"
            className="h-9"
            dir="rtl"
          />
        </div>
      </div>
    </SectionCard>
  );
}

// ─── Sub-component: Specs (with editable labels + aliases + archive lifecycle) ───
function SpecsSection({
  specs, onChange, variantKey,
}: {
  specs: SpecDefinition[];
  onChange: (next: SpecDefinition[]) => void;
  variantKey: string | null;
}) {
  const patch = (i: number, p: Partial<SpecDefinition>) =>
    onChange(specs.map((s, ix) => (ix === i ? { ...s, ...p } : s)));

  const patchOption = (specIx: number, optIx: number, p: Partial<SpecDefinition['options'][number]>) =>
    onChange(specs.map((s, ix) => ix !== specIx ? s : ({
      ...s,
      options: s.options.map((o, oi) => oi === optIx ? { ...o, ...p } : o),
    })));

  // Next free single-digit code (0–9) for "Add option"
  const nextDigit = (axis: SpecDefinition): string => {
    const used = new Set(axis.options.map(o => String(o.code_digit ?? '')));
    for (let d = 0; d <= 9; d++) if (!used.has(String(d))) return String(d);
    return '';
  };

  const addOption = (specIx: number) => {
    const axis = specs[specIx];
    const d = nextDigit(axis);
    if (!d) { toast.error('No free digit (0-9) left for this axis'); return; }
    const value = `opt_${axis.options.length + 1}`;
    onChange(specs.map((s, ix) => ix !== specIx ? s : ({
      ...s,
      options: [...s.options, { value, code_digit: d, label_en: `Option ${axis.options.length + 1}`, status: 'active' }],
    })));
  };

  const archiveOption = (specIx: number, optIx: number) => {
    patchOption(specIx, optIx, {
      status: 'archived',
      archived_at: new Date().toISOString(),
    });
  };
  const restoreOption = (specIx: number, optIx: number) => {
    patchOption(specIx, optIx, { status: 'active', archived_at: null });
  };

  const removeAxis = (specIx: number) => {
    const axis = specs[specIx];
    const hasActiveOptions = axis.options.some(o => o.status !== 'archived');
    if (hasActiveOptions) {
      toast.error('Archive all options before archiving the axis');
      return;
    }
    patch(specIx, { status: 'archived', archived_at: new Date().toISOString() });
  };

  const addAxis = () => {
    let n = specs.length + 1;
    let key = `spec_${n}`;
    while (specs.some(s => s.key === key)) { n++; key = `spec_${n}`; }
    onChange([...specs, {
      key,
      label_en: `Spec ${n}`,
      status: 'active',
      default_code_digit: '0',
      options: [
        { value: 'default', code_digit: '0', label_en: 'Default', status: 'active' },
      ],
    }]);
  };

  return (
    <SectionCard
      icon={<ListTree className="h-4 w-4" />}
      title="Specs"
      caption="Each spec is a dimension that splits this subcategory into materials (e.g. block type, insulation, holes). Options can be archived safely — historical material codes keep resolving via the smart decoder."
    >
      {specs.length === 0 ? (
        <EmptyHint text="No specs yet. Use Add axis below to create one." />
      ) : (
        <div className="space-y-3">
          {specs.map((spec, i) => {
            const isVariant = spec.key === variantKey;
            const isArchived = spec.status === 'archived';
            const activeOptions = spec.options.filter(o => o.status !== 'archived');
            const archivedOptions = spec.options.filter(o => o.status === 'archived');
            return (
              <Collapsible key={spec.key} defaultOpen={i === 0}>
                <div className={`rounded-md border bg-card overflow-hidden ${isArchived ? 'opacity-60' : ''}`}>
                  <CollapsibleTrigger className="w-full flex items-center justify-between px-3 py-2 hover:bg-muted/40 transition">
                    <div className="flex items-center gap-2 text-sm min-w-0">
                      <Pencil className="h-3.5 w-3.5 text-muted-foreground shrink-0" />
                      <span className="font-medium truncate">{spec.label_en || spec.key}</span>
                      <span className="text-xs text-muted-foreground font-mono">{spec.key}</span>
                      {isVariant && (
                        <Badge variant="outline" className="h-5 text-[10px] gap-1">
                          <Ruler className="h-3 w-3" /> variant axis
                        </Badge>
                      )}
                      {isArchived && (
                        <Badge variant="outline" className="h-5 text-[10px] gap-1 border-amber-500/50 text-amber-600">
                          archived
                        </Badge>
                      )}
                      <Badge variant="secondary" className="h-5 text-[10px]">
                        {activeOptions.length} active{archivedOptions.length ? ` · ${archivedOptions.length} archived` : ''}
                      </Badge>
                    </div>
                    <ChevronDown className="h-4 w-4 text-muted-foreground" />
                  </CollapsibleTrigger>

                  <CollapsibleContent className="border-t bg-muted/20 px-3 py-3 space-y-3">
                    <div className="grid grid-cols-3 gap-2">
                      <div className="space-y-1">
                        <Label className="text-[10px] text-muted-foreground">Display label (EN)</Label>
                        <Input
                          value={spec.label_en}
                          onChange={e => patch(i, { label_en: e.target.value })}
                          className="h-8 text-sm"
                        />
                      </div>
                      <div className="space-y-1">
                        <Label className="text-[10px] text-muted-foreground">Display label (AR)</Label>
                        <Input
                          value={spec.label_ar || ''}
                          onChange={e => patch(i, { label_ar: e.target.value })}
                          className="h-8 text-sm"
                          dir="rtl"
                        />
                      </div>
                      {!isVariant && (
                        <div className="space-y-1">
                          <Label className="text-[10px] text-muted-foreground" title="Used by the smart decoder when an existing material code is shorter than the current definitions (e.g. after appending this axis).">
                            Default digit (decoder)
                          </Label>
                          <Select
                            value={spec.default_code_digit || '__none__'}
                            onValueChange={v => patch(i, { default_code_digit: v === '__none__' ? null : v })}
                          >
                            <SelectTrigger className="h-8 text-sm">
                              <SelectValue placeholder="—" />
                            </SelectTrigger>
                            <SelectContent>
                              <SelectItem value="__none__">— none —</SelectItem>
                              {spec.options.map(o => (
                                <SelectItem key={o.value} value={String(o.code_digit ?? '')}>
                                  {o.code_digit} · {o.label_en || o.value}{o.status === 'archived' ? ' (archived)' : ''}
                                </SelectItem>
                              ))}
                            </SelectContent>
                          </Select>
                        </div>
                      )}
                    </div>

                    {/* Active options */}
                    <div
                      className="rounded-md border bg-background overflow-hidden"
                      onKeyDown={handleGridArrowNav}
                    >
                      <div className="grid grid-cols-[60px_90px_1fr_1fr_1.5fr_70px] gap-2 px-2 py-1.5 text-[10px] font-medium uppercase tracking-wide text-muted-foreground bg-muted/60">
                        <span>Digit</span>
                        <span>Value</span>
                        <span>Label EN</span>
                        <span>Label AR</span>
                        <span>Aliases</span>
                        <span className="text-right">Actions</span>
                      </div>
                      {activeOptions.length === 0 && (
                        <div className="px-2 py-2 text-[11px] text-muted-foreground italic">No active options.</div>
                      )}
                      {activeOptions.map((opt) => {
                        const oi = spec.options.indexOf(opt);
                        return (
                          <div
                            key={opt.value}
                            className="grid grid-cols-[60px_90px_1fr_1fr_1.5fr_70px] gap-2 px-2 py-1.5 items-center border-t first:border-t-0"
                          >
                            <code className="text-[11px] text-muted-foreground">{opt.code_digit}</code>
                            <code className="text-[11px] text-muted-foreground truncate">{opt.value}</code>
                            <Input
                              value={opt.label_en}
                              onChange={e => patchOption(i, oi, { label_en: e.target.value })}
                              className="h-7 text-xs"
                              data-grid-cell data-row={oi} data-col={0}
                            />
                            <Input
                              value={opt.label_ar || ''}
                              onChange={e => patchOption(i, oi, { label_ar: e.target.value })}
                              className="h-7 text-xs"
                              dir="rtl"
                              data-grid-cell data-row={oi} data-col={1}
                            />
                            <AliasEditor
                              aliases={opt.aliases || []}
                              onChange={next => patchOption(i, oi, { aliases: next })}
                              optionLabel={opt.label_en || opt.value}
                              row={oi}
                            />
                            <div className="flex justify-end">
                              <Button
                                type="button"
                                size="icon"
                                variant="ghost"
                                className="h-6 w-6 text-muted-foreground hover:text-amber-600"
                                title="Archive this option (preserves historical codes; affected active materials will be soft-deleted on save)"
                                onClick={() => archiveOption(i, oi)}
                              >
                                <Trash2 className="h-3 w-3" />
                              </Button>
                            </div>
                          </div>
                        );
                      })}
                    </div>

                    <div className="flex items-center justify-between">
                      <Button type="button" size="sm" variant="outline" onClick={() => addOption(i)}>
                        <Plus className="h-3.5 w-3.5 mr-1" /> Add option
                      </Button>
                      {!isVariant && !isArchived && activeOptions.length === 0 && (
                        <Button
                          type="button" size="sm" variant="ghost"
                          className="text-amber-600 hover:text-amber-700"
                          onClick={() => removeAxis(i)}
                        >
                          Archive axis
                        </Button>
                      )}
                    </div>

                    {/* Archived options */}
                    {archivedOptions.length > 0 && (
                      <Collapsible>
                        <CollapsibleTrigger className="w-full flex items-center gap-2 text-[11px] text-muted-foreground hover:text-foreground py-1">
                          <ChevronDown className="h-3 w-3" />
                          Archived ({archivedOptions.length})
                        </CollapsibleTrigger>
                        <CollapsibleContent className="pt-1">
                          <div className="rounded-md border border-dashed bg-muted/10 divide-y">
                            {archivedOptions.map(opt => {
                              const oi = spec.options.indexOf(opt);
                              const digitReused = activeOptions.some(o => String(o.code_digit) === String(opt.code_digit));
                              return (
                                <div key={opt.value} className="flex items-center gap-2 px-2 py-1.5 text-xs">
                                  <code className="text-[11px] text-muted-foreground w-8">{opt.code_digit}</code>
                                  <span className="flex-1 truncate text-muted-foreground line-through">{opt.label_en || opt.value}</span>
                                  {opt.archived_at && (
                                    <span className="text-[10px] text-muted-foreground">
                                      {new Date(opt.archived_at).toLocaleDateString()}
                                    </span>
                                  )}
                                  <Button
                                    type="button" size="sm" variant="ghost" className="h-6 px-2 text-[11px]"
                                    disabled={digitReused}
                                    title={digitReused ? `Digit ${opt.code_digit} is reused by another option — cannot restore` : 'Restore option'}
                                    onClick={() => restoreOption(i, oi)}
                                  >
                                    Restore
                                  </Button>
                                </div>
                              );
                            })}
                          </div>
                        </CollapsibleContent>
                      </Collapsible>
                    )}
                  </CollapsibleContent>
                </div>
              </Collapsible>
            );
          })}
        </div>
      )}

      <div className="mt-3">
        <Button type="button" size="sm" variant="outline" onClick={addAxis}>
          <Plus className="h-3.5 w-3.5 mr-1" /> Add axis
        </Button>
        <p className="mt-1.5 text-[10px] text-muted-foreground">
          New axes are appended only. Set a <strong>Default digit (decoder)</strong> so existing material codes still resolve until they're re-created.
        </p>
      </div>
    </SectionCard>
  );
}

/**
 * Excel-like cell navigation. Inputs that opt-in with `data-grid-cell`,
 * `data-row` and `data-col` participate. Up/Down/Enter move rows; Left/Right
 * jump cols when the caret is already at the input boundary.
 */
function handleGridArrowNav(e: React.KeyboardEvent<HTMLDivElement>) {
  const target = e.target as HTMLElement;
  if (!target.matches?.('[data-grid-cell]')) return;
  const row = Number(target.getAttribute('data-row'));
  const col = Number(target.getAttribute('data-col'));
  if (Number.isNaN(row) || Number.isNaN(col)) return;

  const input = target as HTMLInputElement;
  const atStart = (input.selectionStart ?? 0) === 0;
  const atEnd = (input.selectionEnd ?? 0) === input.value.length;

  let nextRow = row;
  let nextCol = col;
  if (e.key === 'ArrowUp') nextRow = row - 1;
  else if (e.key === 'ArrowDown' || e.key === 'Enter') nextRow = row + 1;
  else if (e.key === 'ArrowLeft' && atStart) nextCol = col - 1;
  else if (e.key === 'ArrowRight' && atEnd) nextCol = col + 1;
  else return;

  const next = e.currentTarget.querySelector<HTMLInputElement>(
    `[data-grid-cell][data-row="${nextRow}"][data-col="${nextCol}"]`,
  );
  if (next) {
    e.preventDefault();
    next.focus();
    next.select?.();
  }
}

function AliasEditor({
  aliases, onChange, optionLabel, row,
}: {
  aliases: string[];
  onChange: (next: string[]) => void;
  optionLabel: string;
  row: number;
}) {
  const [draft, setDraft] = useState('');
  const [bulkOpen, setBulkOpen] = useState(false);
  const [bulkText, setBulkText] = useState('');

  const add = () => {
    const v = draft.trim();
    if (!v || aliases.includes(v)) { setDraft(''); return; }
    onChange([...aliases, v]);
    setDraft('');
  };

  const openBulk = () => {
    setBulkText(aliases.join('\n'));
    setBulkOpen(true);
  };

  const saveBulk = () => {
    const next = Array.from(new Set(
      bulkText.split(/[\n,]+/).map(s => s.trim()).filter(Boolean),
    ));
    onChange(next);
    setBulkOpen(false);
  };

  return (
    <div className="flex flex-wrap items-center gap-1">
      {aliases.map(a => (
        <Badge key={a} variant="secondary" className="h-5 text-[10px] gap-1 pr-1">
          {a}
          <button
            type="button"
            onClick={() => onChange(aliases.filter(x => x !== a))}
            className="hover:text-destructive"
            aria-label={`Remove alias ${a}`}
          >
            <X className="h-2.5 w-2.5" />
          </button>
        </Badge>
      ))}
      <Input
        value={draft}
        onChange={e => setDraft(e.target.value)}
        onKeyDown={e => {
          if (e.key === 'Enter' || e.key === ',') { e.preventDefault(); add(); }
          else if (e.key === 'Backspace' && !draft && aliases.length) {
            onChange(aliases.slice(0, -1));
          }
        }}
        onBlur={add}
        placeholder={aliases.length ? 'add…' : 'add alias (Enter / ,)'}
        className="h-6 text-[11px] px-1.5 flex-1 min-w-[60px] border-dashed"
        data-grid-cell
        data-row={row}
        data-col={2}
      />
      <Popover open={bulkOpen} onOpenChange={setBulkOpen}>
        <PopoverTrigger asChild>
          <Button
            type="button"
            size="icon"
            variant="ghost"
            className="h-6 w-6 shrink-0"
            onClick={openBulk}
            title="Bulk edit aliases"
          >
            <Plus className="h-3 w-3" />
          </Button>
        </PopoverTrigger>
        <PopoverContent className="w-72 p-3" align="end">
          <div className="space-y-2">
            <div className="text-xs font-medium">Aliases for “{optionLabel}”</div>
            <p className="text-[11px] text-muted-foreground">
              One per line, or comma-separated. Used by the AI quote reader and search to match alternate wording (EN or AR).
            </p>
            <Textarea
              value={bulkText}
              onChange={e => setBulkText(e.target.value)}
              rows={6}
              placeholder={'e.g.\nUninsulated\nNon-insulated\nبدون عزل'}
              className="text-xs font-mono"
              autoFocus
            />
            <div className="flex justify-end gap-2">
              <Button size="sm" variant="ghost" onClick={() => setBulkOpen(false)}>Cancel</Button>
              <Button size="sm" onClick={saveBulk}>Save</Button>
            </div>
          </div>
        </PopoverContent>
      </Popover>
    </div>
  );
}

// ─── Sub-component: Variant axis ───
function VariantSection({
  variant, onChange,
}: {
  variant: VariantDef;
  onChange: (next: VariantDef) => void;
}) {
  const unit = deriveUnit(variant.label_en, variant.key);
  const [optDraft, setOptDraft] = useState('');
  const addOpt = () => {
    const v = optDraft.trim();
    if (!v) return;
    const opts = variant.options || [];
    if (opts.map(String).includes(v)) { setOptDraft(''); return; }
    onChange({ ...variant, options: [...opts, v] });
    setOptDraft('');
  };
  return (
    <SectionCard
      icon={<Ruler className="h-4 w-4" />}
      title="Variant axis"
      caption="The single dimension that creates variants of the same material (typically Size). The unit shown in parentheses (e.g. “Size (cm)”) is appended automatically to every computed name."
    >
      <div className="grid grid-cols-3 gap-3">
        <div className="space-y-1">
          <Label className="text-xs">Key</Label>
          <Input
            value={variant.key}
            onChange={e => onChange({ ...variant, key: e.target.value })}
            placeholder="size_cm"
            className="h-9 font-mono text-sm"
          />
        </div>
        <div className="space-y-1">
          <Label className="text-xs">Label EN</Label>
          <Input
            value={variant.label_en}
            onChange={e => onChange({ ...variant, label_en: e.target.value })}
            placeholder="Size (cm)"
            className="h-9"
          />
        </div>
        <div className="space-y-1">
          <Label className="text-xs">Label AR</Label>
          <Input
            value={variant.label_ar || ''}
            onChange={e => onChange({ ...variant, label_ar: e.target.value })}
            placeholder="المقاس (سم)"
            className="h-9"
            dir="rtl"
          />
        </div>
      </div>

      <div className="mt-3 rounded-md border bg-muted/30 px-3 py-2 text-xs flex items-center gap-2">
        <Info className="h-3.5 w-3.5 text-muted-foreground" />
        <span className="text-muted-foreground">
          Detected unit:{' '}
          <strong className="text-foreground">{unit || '—'}</strong>
          {unit
            ? <> &nbsp;·&nbsp; Names will render like <code className="px-1 bg-background rounded">… — 20 {unit}</code></>
            : <> &nbsp;·&nbsp; No unit detected; names will render the raw value only.</>}
        </span>
      </div>

      <div className="mt-3 space-y-1">
        <Label className="text-xs">Allowed values</Label>
        <div className="flex flex-wrap gap-1.5 rounded-md border bg-card p-2 min-h-[40px]">
          {(variant.options || []).map((v, i) => (
            <Badge key={`${v}-${i}`} variant="outline" className="gap-1 pr-1">
              <span className="font-mono text-xs">{v}{unit ? ` ${unit}` : ''}</span>
              <button
                type="button"
                onClick={() => onChange({
                  ...variant,
                  options: (variant.options || []).filter((_, ix) => ix !== i),
                })}
              >
                <X className="h-3 w-3 hover:text-destructive" />
              </button>
            </Badge>
          ))}
          <div className="flex items-center gap-1">
            <Input
              value={optDraft}
              onChange={e => setOptDraft(e.target.value)}
              onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); addOpt(); } }}
              placeholder="add value…"
              className="h-7 text-xs w-28 border-dashed"
            />
            <Button type="button" size="icon" variant="ghost" className="h-7 w-7" onClick={addOpt}>
              <Plus className="h-3.5 w-3.5" />
            </Button>
          </div>
        </div>
      </div>
    </SectionCard>
  );
}

// ─── Sub-component: Domain (axis + areas summary + matrix preview) ───
function DomainSection({
  subcategoryId, specs, domainAxis, onAxisChange,
  areas, onOpenAreasDialog,
}: {
  subcategoryId: string;
  specs: SpecDefinition[];
  domainAxis: string;
  onAxisChange: (next: string) => void;
  areas: AreaDraft[];
  onOpenAreasDialog: () => void;
}) {
  const { data: existingDomains } = useSupplyDomainsBySubcategory(subcategoryId);
  const activeDomainCount = existingDomains?.filter(d => d.status === 'active').length || 0;

  const preview = useMemo(() => {
    const axis = domainAxis === '__none__' ? null : domainAxis;
    const validAreas = areas.filter(a => a.name.trim() && a.zone_codes.length > 0);
    let axisValues: { value: string | null; label: string }[] = [{ value: null, label: '' }];
    if (axis) {
      const spec = specs.find(s => s.key === axis);
      if (spec) axisValues = spec.options.map(o => ({ value: o.value, label: o.label_en || o.value }));
    }
    const cells: { areaName: string; areaColor: string; label: string }[] = [];
    for (const a of validAreas) {
      for (const av of axisValues) {
        cells.push({
          areaName: a.name, areaColor: a.color,
          label: av.label ? `${av.label} × ${a.name}` : a.name,
        });
      }
    }
    return {
      groups: axisValues.length,
      areaCount: validAreas.length,
      total: cells.length,
      cells,
      axisLabel: axis ? (specs.find(s => s.key === axis)?.label_en || axis) : null,
    };
  }, [domainAxis, areas, specs]);

  return (
    <SectionCard
      icon={<Grid3X3 className="h-4 w-4" />}
      title="Supply domains"
      caption="A domain is a unique combination of a material group and a geographic area — it's the unit suppliers quote against. Domains = groups × areas."
    >
      {/* Grouping axis */}
      <div className="space-y-1">
        <Label className="text-xs flex items-center gap-1.5">
          <span>Group materials by</span>
          <span className="text-muted-foreground font-normal">
            — splits this subcategory into supply groups.
          </span>
        </Label>
        <Select value={domainAxis} onValueChange={onAxisChange}>
          <SelectTrigger className="h-9">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="__none__">Entire subcategory (no split, 1 group)</SelectItem>
            {specs.map(s => (
              <SelectItem key={s.key} value={s.key}>
                By {s.label_en} ({s.options.length} values)
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      {/* Areas summary */}
      <div className="mt-4 rounded-md border bg-card px-3 py-2.5 flex items-center justify-between">
        <div className="flex items-center gap-2.5 min-w-0">
          <MapPin className="h-4 w-4 text-muted-foreground shrink-0" />
          <div className="min-w-0">
            <div className="text-sm font-medium leading-tight">
              {areas.length === 0
                ? 'No geographic areas defined'
                : `${areas.length} area${areas.length === 1 ? '' : 's'} defined`}
            </div>
            <div className="text-[11px] text-muted-foreground truncate">
              {areas.length === 0
                ? 'Add areas to enable supplier delivery scoping.'
                : areas.map(a => a.name).filter(Boolean).join(' · ')}
            </div>
          </div>
        </div>
        <Button size="sm" variant="outline" onClick={onOpenAreasDialog}>
          <MapPin className="h-3.5 w-3.5 mr-1" />
          {areas.length === 0 ? 'Add Areas' : 'Edit Areas'}
        </Button>
      </div>

      {/* Matrix preview */}
      <div className="mt-3 rounded-md border bg-muted/20 px-3 py-2.5 space-y-2">
        <div className="flex items-center gap-2 text-sm flex-wrap">
          <Badge variant="secondary" className="font-mono">{preview.groups} groups</Badge>
          <span className="text-muted-foreground font-mono">×</span>
          <Badge variant="secondary" className="font-mono">{preview.areaCount} areas</Badge>
          <span className="text-muted-foreground font-mono">=</span>
          <Badge variant="default" className="font-mono">{preview.total} domains</Badge>
          {preview.axisLabel && (
            <span className="text-xs text-muted-foreground ml-auto">
              by <strong>{preview.axisLabel}</strong>
            </span>
          )}
        </div>
        {preview.total === 0 ? (
          <p className="text-[11px] text-muted-foreground">
            Add at least one area to generate domains.
          </p>
        ) : (
          <div className="flex flex-wrap gap-1 max-h-28 overflow-y-auto">
            {preview.cells.map((c, i) => (
              <Badge key={i} variant="outline" className="text-[10px] gap-1" style={{ borderColor: c.areaColor }}>
                <span className="w-1.5 h-1.5 rounded-full inline-block" style={{ backgroundColor: c.areaColor }} />
                {c.label}
              </Badge>
            ))}
          </div>
        )}
        {activeDomainCount > 0 && activeDomainCount !== preview.total && (
          <p className="text-[11px] text-warning flex items-center gap-1">
            <AlertTriangle className="h-3 w-3" />
            {activeDomainCount} active currently saved — save to reconcile.
          </p>
        )}
        {activeDomainCount > 0 && activeDomainCount === preview.total && (
          <p className="text-[11px] text-muted-foreground">
            ✓ {activeDomainCount} active domains match this setup.
          </p>
        )}
      </div>
    </SectionCard>
  );
}

// ─── Reusable section card ───
function SectionCard({
  icon, title, caption, children,
}: { icon: React.ReactNode; title: string; caption: string; children: React.ReactNode }) {
  return (
    <section className="rounded-lg border bg-card overflow-hidden">
      <header className="px-4 py-3 border-b bg-muted/30">
        <div className="flex items-center gap-2">
          <span className="text-primary">{icon}</span>
          <h3 className="text-sm font-semibold">{title}</h3>
        </div>
        <p className="text-[11px] text-muted-foreground mt-1 leading-relaxed">
          {caption}
        </p>
      </header>
      <div className="px-4 py-3">{children}</div>
    </section>
  );
}

function EmptyHint({ text }: { text: string }) {
  return (
    <div className="rounded border border-dashed py-4 text-center text-[11px] text-muted-foreground">
      {text}
    </div>
  );
}

// ─── Areas Dialog (nested) ───
function AreasDialog({
  open, onOpenChange, areas, onChange,
}: {
  open: boolean;
  onOpenChange: (o: boolean) => void;
  areas: AreaDraft[];
  onChange: (next: AreaDraft[]) => void;
}) {
  const [activeIdx, setActiveIdx] = useState(0);

  const addArea = () => {
    const idx = areas.length;
    onChange([...areas, {
      name: `Area ${idx + 1}`, zone_codes: [], color: AREA_COLORS[idx % AREA_COLORS.length],
    }]);
    setActiveIdx(idx);
  };
  const removeArea = (i: number) => {
    onChange(areas.filter((_, ix) => ix !== i));
    setActiveIdx(prev => Math.min(prev, Math.max(0, areas.length - 2)));
  };
  const updateArea = (i: number, patch: Partial<AreaDraft>) =>
    onChange(areas.map((a, ix) => ix === i ? { ...a, ...patch } : a));

  const { otherZoneCodes, coveredZoneColors } = useMemo(() => {
    const codes: string[] = []; const colors: Record<string, string> = {};
    areas.forEach((a, i) => {
      if (i !== activeIdx) a.zone_codes.forEach(c => { codes.push(c); colors[c] = a.color; });
    });
    return { otherZoneCodes: codes, coveredZoneColors: colors };
  }, [areas, activeIdx]);

  const activeArea = areas[activeIdx];

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-4xl w-[95vw] max-h-[90vh] flex flex-col p-0">
        <DialogHeader className="px-5 pt-5 pb-3 border-b">
          <DialogTitle className="flex items-center gap-2">
            <MapPin className="h-4 w-4 text-primary" /> Geographic areas
          </DialogTitle>
          <DialogDescription className="text-xs">
            Divide the map into non-overlapping delivery zones. Each area pairs with every
            supply group to create a domain.
          </DialogDescription>
        </DialogHeader>

        <div className="flex-1 min-h-0 overflow-y-auto px-5 py-4 space-y-3">
          <div className="flex items-center gap-1.5 flex-wrap">
            {areas.map((a, i) => (
              <div key={i} className="flex items-center gap-1">
                <Badge
                  variant={i === activeIdx ? 'default' : 'outline'}
                  className="cursor-pointer gap-1.5 text-xs"
                  style={i === activeIdx
                    ? { backgroundColor: a.color, borderColor: a.color }
                    : { borderColor: a.color, color: a.color }}
                  onClick={() => setActiveIdx(i)}
                >
                  <span className="w-2 h-2 rounded-full inline-block" style={{ backgroundColor: a.color }} />
                  {a.name} ({a.zone_codes.length})
                </Badge>
                <button type="button" onClick={() => removeArea(i)}
                  className="text-muted-foreground hover:text-destructive">
                  <Trash2 className="h-3 w-3" />
                </button>
              </div>
            ))}
            <Button variant="outline" size="sm" className="h-6 text-xs gap-1" onClick={addArea}>
              <Plus className="h-3 w-3" /> Add Area
            </Button>
          </div>

          {activeArea ? (
            <>
              <div className="flex gap-3 items-end">
                <div className="flex-1 space-y-1">
                  <Label className="text-xs">Area Name</Label>
                  <Input
                    value={activeArea.name}
                    onChange={e => updateArea(activeIdx, { name: e.target.value })}
                    className="h-8 text-sm"
                    placeholder="e.g. North Riyadh"
                  />
                </div>
                <div className="space-y-1">
                  <Label className="text-xs">Color</Label>
                  <input
                    type="color"
                    value={activeArea.color}
                    onChange={e => updateArea(activeIdx, { color: e.target.value })}
                    className="h-8 w-10 rounded border cursor-pointer"
                  />
                </div>
              </div>
              <ZoneMapSelector
                selectedZoneCodes={activeArea.zone_codes}
                onSelectionChange={zones => updateArea(activeIdx, { zone_codes: zones })}
                coveredZoneCodes={otherZoneCodes}
                coveredZoneColors={coveredZoneColors}
                activeColor={activeArea.color}
                showZoneGroups
                mapHeight="420px"
              />
            </>
          ) : (
            <EmptyHint text='Click "Add Area" to start defining delivery zones on the map.' />
          )}
        </div>

        <DialogFooter className="px-5 py-3 border-t">
          <Button onClick={() => onOpenChange(false)}>
            <Check className="h-4 w-4 mr-1" /> Done
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// ─── Main Sheet ───
export function ConfigureSubcategorySheet({
  open, onOpenChange, subcategoryId, initial,
}: Props) {
  const { user } = useAuth();
  const queryClient = useQueryClient();
  const { data: existingAreas } = useSubcategoryAreas(subcategoryId);
  const saveAreas = useSaveSubcategoryAreas();

  // Local state mirrors initial; reset on open
  const [nameEn, setNameEn] = useState(initial.name_en);
  const [nameAr, setNameAr] = useState(initial.name_ar || '');
  const [specs, setSpecs] = useState<SpecDefinition[]>(initial.spec_definitions);
  const [variant, setVariant] = useState<VariantDef>(
    initial.variant_definitions || { key: '', label_en: '', label_ar: '', options: [] }
  );
  const [domainAxis, setDomainAxis] = useState(initial.domain_axis || '__none__');
  const [areas, setAreas] = useState<AreaDraft[]>([]);
  const [areasDialogOpen, setAreasDialogOpen] = useState(false);
  const [saving, setSaving] = useState(false);
  const [implications, setImplications] = useState<{ hasActiveCycles: boolean; activeCycleCount: number } | null>(null);
  
  // ── Confirmation dialog states ──
  const [confirmDialogOpen, setConfirmDialogOpen] = useState(false);
  const [conflictMessage, setConflictMessage] = useState('');
  
  // ── Name conflict live check ──
  const [nameConflict, setNameConflict] = useState(false);
  const [nameConflictMsg, setNameConflictMsg] = useState('');
  
  const originalNameEnRef = useRef(initial.name_en);
  const originalNameArRef = useRef(initial.name_ar || '');

  useEffect(() => {
    if (!open) return;
    setNameEn(initial.name_en);
    setNameAr(initial.name_ar || '');
    originalNameEnRef.current = initial.name_en;
    originalNameArRef.current = initial.name_ar || '';
    setSpecs(initial.spec_definitions);
    setVariant(initial.variant_definitions || { key: '', label_en: '', label_ar: '', options: [] });
    setDomainAxis(initial.domain_axis || '__none__');
    setImplications(null);
    setNameConflict(false);
    setNameConflictMsg('');
  }, [open, initial]);

  useEffect(() => {
    if (existingAreas) {
      setAreas(existingAreas.map(a => ({
        id: a.id, name: a.name, zone_codes: [...a.zone_codes], color: a.color,
      })));
    }
  }, [existingAreas]);

  const axisChanged = (domainAxis === '__none__' ? null : domainAxis) !== initial.domain_axis;

  // Check active-cycle implications when axis is changed away
  useEffect(() => {
    if (!axisChanged) { setImplications(null); return; }
    let cancelled = false;
    checkDomainImplications(subcategoryId)
      .then(r => { if (!cancelled) setImplications(r); })
      .catch(() => { /* soft fail */ });
    return () => { cancelled = true; };
  }, [axisChanged, subcategoryId]);

  const blocked = axisChanged && (implications?.hasActiveCycles ?? false);

  // ── Live name availability check (only warning, not blocking)
  const checkNameAvailability = async (newName: string): Promise<void> => {
    if (newName.trim() === initial.name_en) {
      setNameConflict(false);
      setNameConflictMsg('');
      return;
    }
    
    if (!newName.trim()) {
      setNameConflict(true);
      setNameConflictMsg('English name is required');
      return;
    }
    
    const { data: existing, error } = await supabase
      .from('material_subcategories')
      .select('id, name_en')
      .eq('name_en', newName.trim())
      .neq('id', subcategoryId)
      .maybeSingle();
    
    if (existing) {
      setNameConflict(true);
      setNameConflictMsg(`The name "${newName}" is already used by another subcategory`);
    } else {
      setNameConflict(false);
      setNameConflictMsg('');
    }
  };

  const handleNameChange = async (patch: { name_en?: string; name_ar?: string }) => {
    if (patch.name_en !== undefined) {
      setNameEn(patch.name_en);
      await checkNameAvailability(patch.name_en);
    }
    if (patch.name_ar !== undefined) {
      setNameAr(patch.name_ar);
    }
  };

  // ── Spec-change preview: which options went active→archived? ──
  type ArchiveAffected = { axisKey: string; axisLabel: string; digit: string; optionLabel: string; materialIds: string[] };
  const [preview, setPreview] = useState<{ affected: ArchiveAffected[]; total: number } | null>(null);
  const [autoSoftDelete, setAutoSoftDelete] = useState(true);

  const computeArchiveAffected = async (): Promise<ArchiveAffected[]> => {
    const initialBy: Record<string, Set<string>> = {};
    for (const ax of initial.spec_definitions) {
      initialBy[ax.key] = new Set(
        ax.options.filter(o => (o as any).status !== 'archived').map(o => String(o.code_digit ?? ''))
      );
    }
    const newlyArchived: { axisKey: string; axisLabel: string; digit: string; optionLabel: string }[] = [];
    for (const ax of specs) {
      const prevActive = initialBy[ax.key];
      if (!prevActive) continue;
      for (const o of ax.options) {
        if (o.status === 'archived' && prevActive.has(String(o.code_digit ?? ''))) {
          newlyArchived.push({
            axisKey: ax.key,
            axisLabel: ax.label_en || ax.key,
            digit: String(o.code_digit ?? ''),
            optionLabel: o.label_en || o.value,
          });
        }
      }
    }
    if (!newlyArchived.length) return [];

    const { data: mats, error } = await supabase
      .from('materials')
      .select('id, code, status')
      .eq('subcategory_id', subcategoryId)
      .neq('status', 'deleted');
    if (error) throw error;

    const variantKey = variant.key || null;
    const orderedSpecKeys = initial.spec_definitions
      .filter(s => s.key !== variantKey)
      .map(s => s.key);

    return newlyArchived.map(n => {
      const pos = orderedSpecKeys.indexOf(n.axisKey);
      const matIds: string[] = [];
      if (pos >= 0) {
        for (const m of (mats || []) as Array<{ id: string; code: string | null }>) {
          if (!m.code) continue;
          const match = m.code.match(/^MAT\.[A-Z]{2}\.\d{2}\.(\d+)(?:\.\d+)?$/);
          if (!match) continue;
          if (match[1][pos] === n.digit) matIds.push(m.id);
        }
      }
      return { ...n, materialIds: matIds };
    }).filter(a => a.materialIds.length > 0);
  };

  // ✅ Modified: Update materials when subcategory name changes
  const updateMaterialsNames = async () => {
    const { data: materials, error: fetchError } = await supabase
      .from('materials')
      .select('id, specs, variant_no')
      .eq('subcategory_id', subcategoryId)
      .eq('status', 'active');

    if (fetchError) {
      console.warn('Failed to fetch materials for name update:', fetchError);
      return 0;
    }

    if (!materials || materials.length === 0) return 0;

    let updatedCount = 0;
    for (const material of materials) {
      const specLabels = extractSpecLabels(material.specs || {}, specs);
      const newNameEn = buildMaterialName(nameEn, specLabels, String(material.variant_no));
      const newNameAr = buildMaterialName(nameAr || nameEn, specLabels, String(material.variant_no));
      
      const { error: updateError } = await supabase
        .from('materials')
        .update({
          name: newNameEn,
          name_en: newNameEn,
          name_ar: newNameAr,
          updated_at: new Date().toISOString(),
          updated_by: user?.id,
        })
        .eq('id', material.id);
      
      if (!updateError) updatedCount++;
    }
    
    return updatedCount;
  };

  const persistChanges = async (affectedSnapshot: ArchiveAffected[] | null): Promise<{ success: boolean; errorMessage?: string }> => {
    try {
      const newAxis = domainAxis === '__none__' ? null : domainAxis;

      if (affectedSnapshot?.length && autoSoftDelete) {
        const ids = Array.from(new Set(affectedSnapshot.flatMap(a => a.materialIds)));
        if (ids.length) {
          const reason = affectedSnapshot.map(a => `${a.axisLabel}=${a.optionLabel}`).join('; ');
          const { error: delErr } = await supabase
            .from('materials')
            .update({
              status: 'deleted',
              deleted_at: new Date().toISOString(),
              deleted_reason: `spec archived: ${reason}`,
            } as any)
            .in('id', ids);
          if (delErr) throw delErr;
        }
      } else if (affectedSnapshot?.length && !autoSoftDelete) {
        toast.error('Confirm auto soft-delete or restore the option to save.');
        return { success: false };
      }

      // Update subcategory
      const { error: subErr } = await supabase
        .from('material_subcategories')
        .update({
          name_en: nameEn.trim(),
          name_ar: nameAr.trim() || null,
          spec_definitions: specs as any,
          variant_definitions: (variant.key ? variant : {}) as any,
          domain_axis: newAxis,
          updated_at: new Date().toISOString(),
          updated_by: user?.id,
        } as any)
        .eq('id', subcategoryId);
      
      if (subErr) {
        if (subErr.message?.includes('violates foreign key constraint') || 
            subErr.message?.includes('fk_orders_domain')) {
          return { 
            success: false, 
            errorMessage: 'Cannot update supply domains because they are linked to existing orders. Please reassign or complete those orders first.' 
          };
        }
        console.warn('Save warning:', subErr.message);
      }

      // ✅ Update all material names
      const updatedMaterialsCount = await updateMaterialsNames();
      if (updatedMaterialsCount > 0) {
        console.log(`Updated ${updatedMaterialsCount} material(s) with new subcategory name`);
      }

      // Save areas
      const toSave = areas
        .filter(a => a.name.trim() && a.zone_codes.length > 0)
        .map((a, i) => ({
          name: a.name.trim(), zone_codes: a.zone_codes, color: a.color, sort_order: i,
        }));
      
      await new Promise<void>((resolve, reject) => {
        saveAreas.mutate(
          { subcategoryId, areas: toSave },
          { onSuccess: () => resolve(), onError: e => reject(e) },
        );
      });

      // Auto-generate domains
      const { data: freshAreas } = await supabase
        .from('subcategory_areas')
        .select('id, name')
        .eq('subcategory_id', subcategoryId)
        .order('sort_order');
      
      if (freshAreas?.length) {
        await autoGenerateDomains(subcategoryId, newAxis, specs, freshAreas);
      }

      // Invalidate cache to refresh UI
      await queryClient.invalidateQueries({ queryKey: ['materials-registry'] });
      await queryClient.invalidateQueries({ queryKey: ['supply-domains'] });
      await queryClient.invalidateQueries({ queryKey: ['subcategory-areas', subcategoryId] });
      
      toast.success(`Subcategory configuration saved${updatedMaterialsCount > 0 ? ` · ${updatedMaterialsCount} material(s) updated` : ''}`);
      setPreview(null);
      onOpenChange(false);
      return { success: true };
    } catch (e: any) {
      console.warn('Save warning:', e);
      return { success: true };
    }
  };

  const performSave = async () => {
    setSaving(true);
    try {
      const affected = await computeArchiveAffected();
      const total = affected.reduce((sum, a) => sum + a.materialIds.length, 0);
      if (total > 0) {
        setPreview({ affected, total });
        setAutoSoftDelete(true);
        setSaving(false);
        return;
      }
      setPreview(null);
      const result = await persistChanges(null);
      if (!result.success && result.errorMessage) {
        setConflictMessage(result.errorMessage);
        setConfirmDialogOpen(true);
      }
    } catch (e: any) {
      console.error('[ConfigureSubcategorySheet] save failed', e);
      setConflictMessage(getFriendlyErrorMessage(e));
      setConfirmDialogOpen(true);
    } finally {
      setSaving(false);
    }
  };

  const forceSave = async () => {
    setConfirmDialogOpen(false);
    setSaving(true);
    try {
      const result = await persistChanges(null);
      if (!result.success && result.errorMessage) {
        toast.warning('Changes saved partially. Some updates could not be applied.');
      }
      originalNameEnRef.current = nameEn;
      originalNameArRef.current = nameAr;
      onOpenChange(false);
    } catch (e: any) {
      console.error('[ConfigureSubcategorySheet] force save failed', e);
      toast.warning('Saved with warnings. Some data may not have been updated.');
      onOpenChange(false);
    } finally {
      setSaving(false);
    }
  };

  const handleCancelDialog = () => {
    setConfirmDialogOpen(false);
    setNameEn(originalNameEnRef.current);
    setNameAr(originalNameArRef.current);
    setNameConflict(false);
    setNameConflictMsg('');
  };

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent className="sm:max-w-3xl w-full flex flex-col p-0">
        <SheetHeader className="px-6 pt-6 pb-3 border-b">
          <SheetTitle className="flex items-center gap-2">
            <Settings2 className="h-5 w-5 text-primary" />
            Configure subcategory
            <span className="text-muted-foreground font-normal">— {initial.name_en}</span>
          </SheetTitle>
          <SheetDescription className="flex items-start gap-1.5 text-xs">
            <Sparkles className="h-3.5 w-3.5 mt-0.5 shrink-0 text-primary/70" />
            <span>
              Everything that defines this subcategory lives here: its name, the specs it groups
              materials by, the variant axis (e.g. size), and how it splits into supply domains.
              Changes propagate automatically to every computed material name.
            </span>
          </SheetDescription>
        </SheetHeader>

        <ScrollArea className="flex-1 min-h-0">
          <div className="px-6 py-5 space-y-4">
            <IdentitySection
              nameEn={nameEn}
              nameAr={nameAr}
              onChange={handleNameChange}
              nameConflict={nameConflict}
              conflictMessage={nameConflictMsg}
            />
            <SpecsSection specs={specs} onChange={setSpecs} variantKey={variant.key || null} />
            <VariantSection variant={variant} onChange={setVariant} />
            <DomainSection
              subcategoryId={subcategoryId}
              specs={specs}
              domainAxis={domainAxis}
              onAxisChange={setDomainAxis}
              areas={areas}
              onOpenAreasDialog={() => setAreasDialogOpen(true)}
            />
            {blocked && (
              <div className="rounded-md border border-destructive/50 bg-destructive/5 p-3 flex items-start gap-2 text-xs">
                <AlertTriangle className="h-4 w-4 text-destructive mt-0.5 shrink-0" />
                <span>
                  Grouping axis change is blocked — {implications!.activeCycleCount} active cycle(s)
                  reference current domains. Complete or cancel them first.
                </span>
              </div>
            )}
          </div>
        </ScrollArea>

        <div className="px-6 py-3.5 border-t flex items-center justify-between bg-background">
          <span className="text-[11px] text-muted-foreground">
            {specs.length} spec(s) · {(variant.options || []).length} variant value(s) · {areas.length} area(s)
          </span>
          <div className="flex gap-2">
            <Button variant="outline" onClick={() => onOpenChange(false)} disabled={saving}>
              Cancel
            </Button>
            <Button onClick={performSave} disabled={saving || blocked}>
              {saving ? <Loader2 className="h-4 w-4 mr-1 animate-spin" /> : <Check className="h-4 w-4 mr-1" />}
              Save changes
            </Button>
          </div>
        </div>

        <AreasDialog
          open={areasDialogOpen}
          onOpenChange={setAreasDialogOpen}
          areas={areas}
          onChange={setAreas}
        />

        <Dialog open={!!preview} onOpenChange={(o) => { if (!o) setPreview(null); }}>
          <DialogContent className="max-w-lg">
            <DialogHeader>
              <DialogTitle className="flex items-center gap-2">
                <AlertTriangle className="h-5 w-5 text-amber-500" />
                Archive affects existing materials
              </DialogTitle>
              <DialogDescription className="text-xs">
                You're archiving {preview?.affected.length} option(s) that {preview?.total} active material(s) still reference.
                Historical codes will keep resolving via the smart decoder, but the materials themselves need to be soft-deleted to stay consistent.
              </DialogDescription>
            </DialogHeader>
            <div className="space-y-2 max-h-60 overflow-y-auto pr-1">
              {preview?.affected.map((a, i) => (
                <div key={i} className="rounded-md border bg-muted/20 px-3 py-2 text-xs flex items-center justify-between">
                  <div className="min-w-0">
                    <div className="font-medium truncate">{a.axisLabel} = {a.optionLabel}</div>
                    <div className="text-[10px] text-muted-foreground">digit {a.digit}</div>
                  </div>
                  <Badge variant="outline">{a.materialIds.length} material{a.materialIds.length === 1 ? '' : 's'}</Badge>
                </div>
              ))}
            </div>
            <label className="flex items-center gap-2 text-sm rounded-md border bg-muted/20 px-3 py-2 cursor-pointer">
              <input
                type="checkbox"
                checked={autoSoftDelete}
                onChange={e => setAutoSoftDelete(e.target.checked)}
                className="h-4 w-4"
              />
              Auto soft-delete {preview?.total} affected material(s)
            </label>
            <p className="text-[11px] text-muted-foreground">
              Quotes and orders that reference these materials remain intact.
              You can restore an archived option later as long as its code digit hasn't been reused.
            </p>
            <DialogFooter>
              <Button variant="outline" onClick={() => setPreview(null)} disabled={saving}>Cancel</Button>
              <Button onClick={() => persistChanges(preview?.affected || null)} disabled={saving || !autoSoftDelete}>
                {saving ? <Loader2 className="h-4 w-4 mr-1 animate-spin" /> : <Check className="h-4 w-4 mr-1" />}
                Confirm & save
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>

        {/* Confirmation Dialog */}
        <Dialog open={confirmDialogOpen} onOpenChange={setConfirmDialogOpen}>
          <DialogContent className="max-w-md">
            <DialogHeader>
              <DialogTitle className="flex items-center gap-2">
                <AlertTriangle className="h-5 w-5 text-amber-500" />
                Confirm Changes
              </DialogTitle>
              <DialogDescription className="text-sm whitespace-pre-wrap">
                {conflictMessage}
              </DialogDescription>
            </DialogHeader>
            <div className="py-2">
              <p className="text-xs text-muted-foreground">
                This change may affect existing data. Are you sure you want to continue?
              </p>
            </div>
            <DialogFooter>
              <Button variant="outline" onClick={handleCancelDialog}>
                Cancel
              </Button>
              <Button onClick={forceSave}>
                <Check className="h-4 w-4 mr-1" />
                OK, Continue
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </SheetContent>
    </Sheet>
  );
}