import { useState, useEffect, useCallback, useMemo, useRef } from 'react';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { ZoneMapSelector } from '@/components/shared/ZoneMapSelector';
import {
  Layers, MapPin, Grid3X3, Plus, Trash2, Loader2, Check, AlertTriangle, RefreshCw, Info,
} from 'lucide-react';
import { toast } from 'sonner';
import { supabase } from '@/integrations/supabase/client';
import { useQueryClient } from '@tanstack/react-query';
import { useSubcategoryAreas, useSaveSubcategoryAreas } from '@/hooks/useSubcategoryAreas';
import {
  autoGenerateDomains,
  checkDomainImplications,
  useSupplyDomainsBySubcategory,
} from '@/hooks/useSupplyDomains';
import type { SpecDefinition } from '@/components/materials/SpecFilterBar';

const AREA_COLORS = ['#f59e0b', '#3b82f6', '#10b981', '#ef4444', '#8b5cf6', '#ec4899', '#06b6d4', '#84cc16'];

interface AreaDraft {
  id?: string;
  name: string;
  zone_codes: string[];
  color: string;
}

interface Props {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  subcategoryId: string;
  subcategoryName: string;
  specDefinitions: SpecDefinition[];
  currentDomainAxis: string | null;
}

export function SubcategorySetupSheet({
  open, onOpenChange, subcategoryId, subcategoryName, specDefinitions, currentDomainAxis,
}: Props) {
  const queryClient = useQueryClient();
  const { data: existingAreas, isLoading: areasLoading } = useSubcategoryAreas(subcategoryId);
  const { data: existingDomains } = useSupplyDomainsBySubcategory(subcategoryId);
  const saveAreas = useSaveSubcategoryAreas();

  // ─── Axis state ───
  const [domainAxis, setDomainAxis] = useState(currentDomainAxis || '__none__');
  const [implications, setImplications] = useState<{ hasActiveCycles: boolean; activeCycleCount: number } | null>(null);
  const [checkingImpl, setCheckingImpl] = useState(false);

  // ─── Areas state ───
  const [areas, setAreas] = useState<AreaDraft[]>([]);
  const [activeIdx, setActiveIdx] = useState(0);

  const [saving, setSaving] = useState(false);

  // Reset on open
  useEffect(() => {
    if (open) {
      setDomainAxis(currentDomainAxis || '__none__');
      setImplications(null);
    }
  }, [open, currentDomainAxis]);

  // Hydrate areas from DB
  useEffect(() => {
    if (existingAreas && existingAreas.length > 0) {
      setAreas(existingAreas.map(a => ({
        id: a.id,
        name: a.name,
        zone_codes: [...a.zone_codes],
        color: a.color,
      })));
      setActiveIdx(0);
    } else if (existingAreas) {
      setAreas([]);
      setActiveIdx(0);
    }
  }, [existingAreas]);

  const axisChanged = (domainAxis === '__none__' ? null : domainAxis) !== currentDomainAxis;

  // ─── Area helpers ───
  const addArea = () => {
    const idx = areas.length;
    setAreas(prev => [...prev, {
      name: `Area ${idx + 1}`,
      zone_codes: [],
      color: AREA_COLORS[idx % AREA_COLORS.length],
    }]);
    setActiveIdx(idx);
  };

  const removeArea = (idx: number) => {
    setAreas(prev => prev.filter((_, i) => i !== idx));
    setActiveIdx(prev => Math.min(prev, Math.max(0, areas.length - 2)));
  };

  const updateAreaName = (idx: number, name: string) =>
    setAreas(prev => prev.map((a, i) => i === idx ? { ...a, name } : a));

  const { otherZoneCodes, coveredZoneColors } = useMemo(() => {
    const codes: string[] = [];
    const colors: Record<string, string> = {};
    areas.forEach((a, i) => {
      if (i !== activeIdx) {
        a.zone_codes.forEach(c => { codes.push(c); colors[c] = a.color; });
      }
    });
    return { otherZoneCodes: codes, coveredZoneColors: colors };
  }, [areas, activeIdx]);

  const activeIdxRef = useRef(activeIdx);
  activeIdxRef.current = activeIdx;

  const handleZoneSelectionChange = useCallback((zoneCodes: string[]) => {
    setAreas(prev => prev.map((a, i) => i === activeIdxRef.current ? { ...a, zone_codes: zoneCodes } : a));
  }, []);

  // ─── Domain preview (live, in-memory) ───
  const preview = useMemo(() => {
    const axis = domainAxis === '__none__' ? null : domainAxis;
    const validAreas = areas.filter(a => a.name.trim() && a.zone_codes.length > 0);

    let axisValues: { value: string | null; label: string }[] = [{ value: null, label: '' }];
    if (axis) {
      const spec = specDefinitions.find(s => s.key === axis);
      if (spec) axisValues = spec.options.map(o => ({ value: o.value, label: o.label_en || o.value }));
    }

    const cells: { axisLabel: string | null; areaName: string; areaColor: string; label: string }[] = [];
    for (const area of validAreas) {
      for (const av of axisValues) {
        const label = av.label ? `${av.label} × ${area.name}` : area.name;
        cells.push({ axisLabel: av.label || null, areaName: area.name, areaColor: area.color, label });
      }
    }

    return {
      axisLabel: axis ? (specDefinitions.find(s => s.key === axis)?.label_en || axis) : null,
      groups: axisValues.length,
      areaCount: validAreas.length,
      total: cells.length,
      cells,
    };
  }, [domainAxis, specDefinitions, areas]);

  // ─── Check axis implications when changed ───
  const handleAxisChange = async (v: string) => {
    setDomainAxis(v);
    setImplications(null);
    const newAxis = v === '__none__' ? null : v;
    if (newAxis !== currentDomainAxis) {
      setCheckingImpl(true);
      try {
        const result = await checkDomainImplications(subcategoryId);
        setImplications(result);
      } catch {
        // soft-fail
      } finally {
        setCheckingImpl(false);
      }
    }
  };

  // ─── Save: persist axis + areas, then regenerate domains ───
  const handleSave = async () => {
    if (axisChanged && implications?.hasActiveCycles) {
      toast.error('Cannot change grouping while active cycles exist');
      return;
    }

    setSaving(true);
    try {
      const newAxis = domainAxis === '__none__' ? null : domainAxis;

      // 1. Update axis if changed
      if (axisChanged) {
        const { error } = await supabase
          .from('material_subcategories')
          .update({ domain_axis: newAxis } as any)
          .eq('id', subcategoryId);
        if (error) throw error;
      }

      // 2. Save areas
      const toSave = areas
        .filter(a => a.name.trim() && a.zone_codes.length > 0)
        .map((a, i) => ({
          name: a.name.trim(),
          zone_codes: a.zone_codes,
          color: a.color,
          sort_order: i,
        }));

      await new Promise<void>((resolve, reject) => {
        saveAreas.mutate(
          { subcategoryId, areas: toSave },
          { onSuccess: () => resolve(), onError: (e) => reject(e) },
        );
      });

      // 3. Re-fetch saved areas (need real IDs) and regenerate domains
      const { data: freshAreas } = await supabase
        .from('subcategory_areas')
        .select('id, name')
        .eq('subcategory_id', subcategoryId)
        .order('sort_order');

      if (freshAreas && freshAreas.length > 0) {
        const result = await autoGenerateDomains(
          subcategoryId,
          newAxis,
          specDefinitions,
          freshAreas,
        );
        toast.success(
          `Domain setup saved · ${preview.total} domain(s) (${result.created} new, ${result.deactivated} deactivated)`
        );
      } else {
        toast.success('Domain setup saved');
      }

      queryClient.invalidateQueries({ queryKey: ['materials-registry'] });
      queryClient.invalidateQueries({ queryKey: ['supply-domains'] });
      queryClient.invalidateQueries({ queryKey: ['subcategory-areas', subcategoryId] });
      onOpenChange(false);
    } catch (err) {
      toast.error(`Failed: ${err instanceof Error ? err.message : String(err)}`);
    } finally {
      setSaving(false);
    }
  };

  const activeArea = areas[activeIdx];
  const activeDomainCount = existingDomains?.filter(d => d.status === 'active').length || 0;
  const blocked = axisChanged && (implications?.hasActiveCycles ?? false);

  // Detect mismatch between actual saved domains and what current axis+areas should produce.
  // This catches cases where the axis was changed previously but domains were never regenerated.
  const mismatch = !axisChanged && preview.total > 0 && preview.total !== activeDomainCount;

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent className="sm:max-w-3xl w-full flex flex-col overflow-hidden p-0">
        <SheetHeader className="px-6 pt-6 pb-3 border-b">
          <SheetTitle className="flex items-center gap-2">
            <Layers className="h-5 w-5 text-primary" />
            Domain Setup — {subcategoryName}
          </SheetTitle>
          <SheetDescription className="flex items-start gap-1.5">
            <Info className="h-3.5 w-3.5 mt-0.5 shrink-0 text-muted-foreground" />
            <span>
              You're configuring <strong>supply domains</strong> for this subcategory — not editing the
              subcategory itself. Domains = <strong>groups × areas</strong>.
            </span>
          </SheetDescription>
        </SheetHeader>

        <ScrollArea className="flex-1 min-h-0">
          <div className="px-6 py-5 space-y-6">

            {/* ─── Mismatch warning ─── */}
            {mismatch && (
              <div className="rounded-md border border-warning/50 bg-warning/10 p-3 flex items-start gap-2">
                <RefreshCw className="h-4 w-4 text-warning mt-0.5 shrink-0" />
                <div className="text-xs flex-1">
                  <p className="font-medium text-foreground">
                    Domain count is out of sync
                  </p>
                  <p className="text-muted-foreground mt-1">
                    Current setup ({preview.groups} group{preview.groups === 1 ? '' : 's'} × {preview.areaCount} area{preview.areaCount === 1 ? '' : 's'}) should produce <strong className="text-foreground">{preview.total} domain{preview.total === 1 ? '' : 's'}</strong>, but only <strong className="text-foreground">{activeDomainCount}</strong> exist. Click <strong>Save Setup</strong> to reconcile.
                  </p>
                </div>
              </div>
            )}

            {/* ─── 1. Grouping axis ─── */}
            <section className="space-y-2">
              <div className="flex items-center gap-2">
                <Grid3X3 className="h-4 w-4 text-muted-foreground" />
                <h3 className="text-sm font-semibold">1. Group materials by</h3>
              </div>
              <p className="text-xs text-muted-foreground">
                Pick the spec axis that splits this subcategory into supply groups.
              </p>
              <Select value={domainAxis} onValueChange={handleAxisChange}>
                <SelectTrigger className="w-full">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="__none__">Entire subcategory (no split, 1 group)</SelectItem>
                  {specDefinitions.map(spec => (
                    <SelectItem key={spec.key} value={spec.key}>
                      By {spec.label_en} ({spec.options.length} values)
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>

              {checkingImpl && (
                <div className="text-xs text-muted-foreground flex items-center gap-1.5">
                  <Loader2 className="h-3 w-3 animate-spin" /> Checking active cycles…
                </div>
              )}

              {blocked && (
                <div className="rounded-md border border-destructive/50 bg-destructive/5 p-3 flex items-start gap-2">
                  <AlertTriangle className="h-4 w-4 text-destructive mt-0.5 shrink-0" />
                  <div className="text-xs">
                    <p className="font-medium text-destructive">Grouping change blocked</p>
                    <p className="text-muted-foreground mt-1">
                      {implications!.activeCycleCount} active cycle(s) reference current domains.
                      Complete or cancel them before changing the grouping axis.
                    </p>
                  </div>
                </div>
              )}
            </section>

            {/* ─── 2. Areas ─── */}
            <section className="space-y-2">
              <div className="flex items-center gap-2">
                <MapPin className="h-4 w-4 text-muted-foreground" />
                <h3 className="text-sm font-semibold">2. Geographic areas</h3>
              </div>
              <p className="text-xs text-muted-foreground">
                Divide the map into non-overlapping delivery areas.
              </p>

              {areasLoading ? (
                <div className="flex items-center justify-center py-12">
                  <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
                </div>
              ) : (
                <div className="space-y-3">
                  <div className="flex items-center gap-2 flex-wrap">
                    {areas.map((area, idx) => (
                      <div key={idx} className="flex items-center gap-1">
                        <Badge
                          variant={idx === activeIdx ? 'default' : 'outline'}
                          className="cursor-pointer gap-1.5 text-xs"
                          style={idx === activeIdx
                            ? { backgroundColor: area.color, borderColor: area.color }
                            : { borderColor: area.color, color: area.color }}
                          onClick={() => setActiveIdx(idx)}
                        >
                          <span className="w-2 h-2 rounded-full inline-block" style={{ backgroundColor: area.color }} />
                          {area.name} ({area.zone_codes.length})
                        </Badge>
                        <button
                          type="button"
                          className="text-muted-foreground hover:text-destructive transition-colors"
                          onClick={() => removeArea(idx)}
                        >
                          <Trash2 className="h-3 w-3" />
                        </button>
                      </div>
                    ))}
                    <Button type="button" variant="outline" size="sm" className="h-6 text-xs gap-1" onClick={addArea}>
                      <Plus className="h-3 w-3" /> Add Area
                    </Button>
                  </div>

                  {activeArea ? (
                    <div className="space-y-3">
                      <div className="flex gap-3 items-end">
                        <div className="flex-1 space-y-1">
                          <Label className="text-xs">Area Name</Label>
                          <Input
                            value={activeArea.name}
                            onChange={e => updateAreaName(activeIdx, e.target.value)}
                            className="h-8 text-sm"
                            placeholder="e.g. North Riyadh"
                          />
                        </div>
                        <div className="space-y-1">
                          <Label className="text-xs">Color</Label>
                          <input
                            type="color"
                            value={activeArea.color}
                            onChange={e => setAreas(prev => prev.map((a, i) => i === activeIdx ? { ...a, color: e.target.value } : a))}
                            className="h-8 w-10 rounded border cursor-pointer"
                          />
                        </div>
                      </div>

                      {/* Map: fixed-height container, ZoneMapSelector renders inside without its own scroll spillover.
                          We DO NOT force h-full because ZoneMapSelector's footer (selected-zones list) needs
                          to flow in normal layout below the map, not overlap it. */}
                      <div>
                        <ZoneMapSelector
                          selectedZoneCodes={activeArea.zone_codes}
                          onSelectionChange={handleZoneSelectionChange}
                          coveredZoneCodes={otherZoneCodes}
                          coveredZoneColors={coveredZoneColors}
                          activeColor={activeArea.color}
                          showZoneGroups
                          mapHeight="420px"
                        />
                      </div>
                    </div>
                  ) : (
                    <div className="rounded-md border border-dashed py-8 text-center text-xs text-muted-foreground">
                      Click "Add Area" to start defining delivery areas on the map.
                    </div>
                  )}
                </div>
              )}
            </section>

            {/* ─── 3. Domain preview ─── */}
            <section className="space-y-2">
              <div className="flex items-center gap-2">
                <Layers className="h-4 w-4 text-muted-foreground" />
                <h3 className="text-sm font-semibold">3. Domain preview</h3>
              </div>
              <p className="text-xs text-muted-foreground">
                Live calculation. The actual domains will be created/reconciled when you save.
              </p>

              <div className="rounded-lg border bg-muted/30 p-3 space-y-3">
                <div className="flex items-center gap-2 text-sm flex-wrap">
                  <Badge variant="secondary" className="font-mono">
                    {preview.groups} group{preview.groups === 1 ? '' : 's'}
                  </Badge>
                  <span className="text-muted-foreground font-mono">×</span>
                  <Badge variant="secondary" className="font-mono">
                    {preview.areaCount} area{preview.areaCount === 1 ? '' : 's'}
                  </Badge>
                  <span className="text-muted-foreground font-mono">=</span>
                  <Badge variant="default" className="font-mono">
                    {preview.total} domain{preview.total === 1 ? '' : 's'}
                  </Badge>
                  {preview.axisLabel && (
                    <span className="text-xs text-muted-foreground ml-auto">
                      Grouped by <strong>{preview.axisLabel}</strong>
                    </span>
                  )}
                </div>

                {preview.total === 0 ? (
                  <p className="text-xs text-warning">
                    Add at least one area with zones to generate domains.
                  </p>
                ) : (
                  <div className="flex flex-wrap gap-1.5 max-h-40 overflow-y-auto">
                    {preview.cells.map((c, i) => (
                      <Badge
                        key={i}
                        variant="outline"
                        className="text-xs gap-1.5"
                        style={{ borderColor: c.areaColor }}
                      >
                        <span className="w-1.5 h-1.5 rounded-full inline-block" style={{ backgroundColor: c.areaColor }} />
                        {c.label}
                      </Badge>
                    ))}
                  </div>
                )}

                {activeDomainCount > 0 && activeDomainCount !== preview.total && (
                  <p className="text-xs text-warning">
                    Currently saved: {activeDomainCount} active domain(s) — does not match preview. Save to reconcile.
                  </p>
                )}
                {activeDomainCount > 0 && activeDomainCount === preview.total && (
                  <p className="text-xs text-muted-foreground">
                    ✓ {activeDomainCount} active domain(s) match this preview.
                  </p>
                )}
              </div>
            </section>
          </div>
        </ScrollArea>

        <div className="px-6 py-4 border-t flex items-center justify-between bg-background">
          <span className="text-xs text-muted-foreground">
            {areas.length} area(s) · {preview.total} domain(s) will exist after save
          </span>
          <div className="flex gap-2">
            <Button variant="outline" onClick={() => onOpenChange(false)} disabled={saving}>
              Cancel
            </Button>
            <Button onClick={handleSave} disabled={saving || checkingImpl || blocked}>
              {(saving || checkingImpl) ? (
                <Loader2 className="h-4 w-4 mr-1 animate-spin" />
              ) : (
                <Check className="h-4 w-4 mr-1" />
              )}
              Save Setup
            </Button>
          </div>
        </div>
      </SheetContent>
    </Sheet>
  );
}
