import { useState, useEffect, useCallback, useMemo, useRef } from 'react';
import { useSubcategoryAreas, useSaveSubcategoryAreas } from '@/hooks/useSubcategoryAreas';
import { autoGenerateDomains } from '@/hooks/useSupplyDomains';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Sheet, SheetContent, SheetHeader, SheetTitle } from '@/components/ui/sheet';
import { ScrollArea } from '@/components/ui/scroll-area';
import { ZoneMapSelector } from '@/components/shared/ZoneMapSelector';
import { MapPin, Plus, Trash2, Loader2, Check } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';

const AREA_COLORS = ['#f59e0b', '#3b82f6', '#10b981', '#ef4444', '#8b5cf6', '#ec4899', '#06b6d4', '#84cc16'];

interface AreaDraft {
  id?: string;
  name: string;
  zone_codes: string[];
  color: string;
}

interface Props {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  subcategoryId: string;
  subcategoryName: string;
  domainAxis?: string | null;
  specDefinitions?: { key: string; label_en: string; options: { value: string; label_en: string }[] }[];
}

export function SubcategoryAreasSheet({ open, onOpenChange, subcategoryId, subcategoryName, domainAxis, specDefinitions }: Props) {
  const { data: existingAreas, isLoading } = useSubcategoryAreas(subcategoryId);
  const saveMut = useSaveSubcategoryAreas();

  const [areas, setAreas] = useState<AreaDraft[]>([]);
  const [activeIdx, setActiveIdx] = useState<number>(0);

  // Initialize from DB
  useEffect(() => {
    if (existingAreas && existingAreas.length > 0) {
      setAreas(existingAreas.map(a => ({
        id: a.id,
        name: a.name,
        zone_codes: [...a.zone_codes],
        color: a.color,
      })));
      setActiveIdx(0);
    } else if (existingAreas && existingAreas.length === 0) {
      setAreas([]);
      setActiveIdx(0);
    }
  }, [existingAreas]);

  const addArea = () => {
    const idx = areas.length;
    setAreas(prev => [...prev, {
      name: `Area ${idx + 1}`,
      zone_codes: [],
      color: AREA_COLORS[idx % AREA_COLORS.length],
    }]);
    setActiveIdx(idx);
  };

  const removeArea = (idx: number) => {
    setAreas(prev => prev.filter((_, i) => i !== idx));
    setActiveIdx(prev => Math.min(prev, Math.max(0, areas.length - 2)));
  };

  const updateAreaName = (idx: number, name: string) => {
    setAreas(prev => prev.map((a, i) => i === idx ? { ...a, name } : a));
  };

  // Zone codes already assigned to OTHER areas (not the active one) + their colors
  const { otherZoneCodes, coveredZoneColors } = useMemo(() => {
    const codes: string[] = [];
    const colors: Record<string, string> = {};
    areas.forEach((a, i) => {
      if (i !== activeIdx) {
        a.zone_codes.forEach(c => {
          codes.push(c);
          colors[c] = a.color;
        });
      }
    });
    return { otherZoneCodes: codes, coveredZoneColors: colors };
  }, [areas, activeIdx]);

  const activeIdxRef = useRef(activeIdx);
  activeIdxRef.current = activeIdx;

  const handleZoneSelectionChange = useCallback((zoneCodes: string[]) => {
    setAreas(prev => prev.map((a, i) => i === activeIdxRef.current ? { ...a, zone_codes: zoneCodes } : a));
  }, []);

  const handleSave = () => {
    const toSave = areas.filter(a => a.name.trim() && a.zone_codes.length > 0).map((a, i) => ({
      name: a.name.trim(),
      zone_codes: a.zone_codes,
      color: a.color,
      sort_order: i,
    }));
    saveMut.mutate(
      { subcategoryId, areas: toSave },
      {
        onSuccess: async () => {
          // Auto-regenerate domains after areas change
          try {
            const savedAreas = toSave.map((a, i) => ({ id: `temp-${i}`, name: a.name }));
            // Re-fetch areas to get real IDs
            const { data: freshAreas } = await supabase
              .from('subcategory_areas')
              .select('id, name')
              .eq('subcategory_id', subcategoryId)
              .order('sort_order');
            if (freshAreas && freshAreas.length > 0) {
              await autoGenerateDomains(
                subcategoryId,
                domainAxis || null,
                specDefinitions || [],
                freshAreas,
              );
            }
          } catch (err) {
            console.error('Domain auto-generation failed:', err);
            toast.error('Areas saved but domain auto-generation failed');
          }
          onOpenChange(false);
        },
      }
    );
  };

  const activeArea = areas[activeIdx];
  const totalZones = areas.reduce((sum, a) => sum + a.zone_codes.length, 0);

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent className="sm:max-w-3xl w-full flex flex-col overflow-hidden">
        <SheetHeader>
          <SheetTitle className="flex items-center gap-2">
            <MapPin className="h-5 w-5 text-primary" />
            Define Areas — {subcategoryName}
          </SheetTitle>
        </SheetHeader>

        <ScrollArea className="flex-1 min-h-0">
          <div className="pr-4 pb-4">
            <p className="text-xs text-muted-foreground mb-3">
              Divide the map into non-overlapping areas for this subcategory. Each area will have its own target price per material.
            </p>

            {isLoading ? (
              <div className="flex items-center justify-center py-20">
                <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
              </div>
            ) : (
              <div className="flex flex-col gap-4">
                {/* Area tabs */}
                <div className="flex items-center gap-2 flex-wrap">
                  {areas.map((area, idx) => (
                    <div key={idx} className="flex items-center gap-1">
                      <Badge
                        variant={idx === activeIdx ? 'default' : 'outline'}
                        className="cursor-pointer gap-1.5 text-xs"
                        style={idx === activeIdx ? { backgroundColor: area.color, borderColor: area.color } : { borderColor: area.color, color: area.color }}
                        onClick={() => setActiveIdx(idx)}
                      >
                        <span className="w-2 h-2 rounded-full inline-block" style={{ backgroundColor: area.color }} />
                        {area.name} ({area.zone_codes.length})
                      </Badge>
                      <button
                        type="button"
                        className="text-muted-foreground hover:text-destructive transition-colors"
                        onClick={() => removeArea(idx)}
                      >
                        <Trash2 className="h-3 w-3" />
                      </button>
                    </div>
                  ))}
                  <Button type="button" variant="outline" size="sm" className="h-6 text-xs gap-1" onClick={addArea}>
                    <Plus className="h-3 w-3" /> Add Area
                  </Button>
                </div>

                {/* Active area editor */}
                {activeArea ? (
                  <div className="flex flex-col gap-3">
                    <div className="flex gap-3 items-end">
                      <div className="flex-1 space-y-1">
                        <Label className="text-xs">Area Name</Label>
                        <Input
                          value={activeArea.name}
                          onChange={e => updateAreaName(activeIdx, e.target.value)}
                          className="h-8 text-sm"
                          placeholder="e.g. North Riyadh"
                        />
                      </div>
                      <div className="space-y-1">
                        <Label className="text-xs">Color</Label>
                        <input
                          type="color"
                          value={activeArea.color}
                          onChange={e => setAreas(prev => prev.map((a, i) => i === activeIdx ? { ...a, color: e.target.value } : a))}
                          className="h-8 w-10 rounded border cursor-pointer"
                        />
                      </div>
                    </div>

                    {/* Map — zones from other areas show as "covered" (green, non-clickable) */}
                    <div className="min-h-[400px]" style={{ height: '50vh' }}>
                      <ZoneMapSelector
                        selectedZoneCodes={activeArea.zone_codes}
                        onSelectionChange={handleZoneSelectionChange}
                        coveredZoneCodes={otherZoneCodes}
                        coveredZoneColors={coveredZoneColors}
                        activeColor={activeArea.color}
                        showZoneGroups
                        mapHeight="100%"
                        className="h-full"
                      />
                    </div>
                  </div>
                ) : (
                  <div className="flex items-center justify-center text-muted-foreground text-sm py-20">
                    Click "Add Area" to start defining delivery areas on the map.
                  </div>
                )}
              </div>
            )}
          </div>
        </ScrollArea>

        <div className="pt-4 border-t flex items-center justify-between">
          <span className="text-xs text-muted-foreground">
            {areas.length} area(s) · {totalZones} zone(s) assigned
          </span>
          <Button onClick={handleSave} disabled={saveMut.isPending}>
            {saveMut.isPending ? <Loader2 className="h-4 w-4 animate-spin mr-1" /> : <Check className="h-4 w-4 mr-1" />}
            Save Areas
          </Button>
        </div>
      </SheetContent>
    </Sheet>
  );
}
