
-- 1. Create agent_table_schema table
CREATE TABLE public.agent_table_schema (
  table_name text PRIMARY KEY,
  module text NOT NULL DEFAULT 'sales',
  description_en text NOT NULL DEFAULT '',
  description_ar text NOT NULL DEFAULT '',
  columns_doc jsonb NOT NULL DEFAULT '[]'::jsonb,
  relationships jsonb NOT NULL DEFAULT '[]'::jsonb,
  read_hints jsonb NOT NULL DEFAULT '[]'::jsonb,
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.agent_table_schema ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can view agent_table_schema"
  ON public.agent_table_schema FOR SELECT TO authenticated
  USING (true);

CREATE POLICY "Admins can manage agent_table_schema"
  ON public.agent_table_schema FOR ALL TO authenticated
  USING (has_role(auth.uid(), 'admin'::app_role))
  WITH CHECK (has_role(auth.uid(), 'admin'::app_role));

-- 2. Seed sales module table schemas
INSERT INTO public.agent_table_schema (table_name, module, description_en, description_ar, columns_doc, relationships, read_hints) VALUES
('accounts', 'sales', 'Master account record for customers and suppliers. Every business entity starts here.', 'السجل الرئيسي للحسابات - عملاء وموردين', 
  '[{"name":"id","type":"uuid","description":"Primary key","required":false},{"name":"display_name","type":"text","description":"Company display name (English)","required":true},{"name":"display_name_ar","type":"text","description":"Company display name (Arabic)","required":false},{"name":"legal_name","type":"text","description":"Official legal/registered name","required":false},{"name":"code","type":"text","description":"Auto-generated code (SAL.NNNN). Read-only.","required":false},{"name":"status","type":"text","description":"active or inactive","required":false,"enum_values":["active","inactive"]},{"name":"tax_number","type":"text","description":"Tax registration number","required":false},{"name":"website","type":"text","description":"Company website URL","required":false},{"name":"location_id","type":"uuid","description":"FK to locations table","required":false},{"name":"poc_contact_id","type":"uuid","description":"FK to contacts - primary point of contact","required":false},{"name":"notes","type":"text","description":"Free-text notes","required":false},{"name":"metadata","type":"jsonb","description":"Extensible metadata object","required":false}]'::jsonb,
  '[{"target_table":"customers","join_key":"account_id","cardinality":"one-to-one","description":"Customer-specific fields"},{"target_table":"contacts","join_key":"account_id","cardinality":"one-to-many","description":"People at this company"},{"target_table":"locations","join_key":"id=location_id","cardinality":"many-to-one","description":"Physical address"},{"target_table":"projects","join_key":"customer_account_id","cardinality":"one-to-many","description":"Projects under this account"}]'::jsonb,
  '["Join with customers ON accounts.id = customers.account_id for customer fields","Join with contacts ON contacts.account_id = accounts.id for POC details","Use customer_list_v1 view for pre-joined customer data"]'::jsonb
),
('contacts', 'sales', 'People associated with an account. Each account can have multiple contacts, one marked as primary.', 'جهات الاتصال المرتبطة بالحسابات',
  '[{"name":"id","type":"uuid","description":"Primary key","required":false},{"name":"account_id","type":"uuid","description":"FK to accounts","required":true},{"name":"full_name","type":"text","description":"Full name (English)","required":true},{"name":"full_name_ar","type":"text","description":"Full name (Arabic)","required":false},{"name":"phone","type":"text","description":"Phone number","required":false},{"name":"email","type":"text","description":"Email address","required":false},{"name":"role_title","type":"text","description":"Job title","required":false},{"name":"is_primary","type":"boolean","description":"Whether this is the primary contact","required":false},{"name":"prefers_whatsapp","type":"boolean","description":"Prefers WhatsApp communication","required":false}]'::jsonb,
  '[{"target_table":"accounts","join_key":"account_id","cardinality":"many-to-one","description":"Parent account"}]'::jsonb,
  '["Filter by is_primary=true to get POC","Filter by account_id to get all contacts for a company"]'::jsonb
),
('customers', 'sales', 'Customer-specific fields extending the accounts table. One-to-one with accounts via account_id.', 'بيانات العميل الإضافية',
  '[{"name":"account_id","type":"uuid","description":"PK and FK to accounts","required":true},{"name":"customer_type","type":"text","description":"SME, Enterprise, Government, Individual","required":false,"enum_values":["SME","Enterprise","Government","Individual"]},{"name":"lifecycle_stage","type":"text","description":"lead, prospect, active, churned","required":false,"enum_values":["lead","prospect","active","churned"]},{"name":"pricing_tier","type":"text","description":"standard, premium, enterprise","required":false},{"name":"payment_terms_days","type":"integer","description":"Payment terms in days","required":false},{"name":"credit_limit","type":"numeric","description":"Credit limit in SAR","required":false},{"name":"assigned_to","type":"uuid","description":"FK to profiles - account owner","required":false}]'::jsonb,
  '[{"target_table":"accounts","join_key":"account_id","cardinality":"one-to-one","description":"Parent account record"}]'::jsonb,
  '["Use customer_list_v1 view for enriched customer data with contact and location info","Filter by lifecycle_stage for pipeline analysis"]'::jsonb
),
('projects', 'sales', 'Customer projects. Every opportunity must belong to a project. A default General project is auto-created when needed.', 'مشاريع العميل',
  '[{"name":"id","type":"uuid","description":"Primary key","required":false},{"name":"customer_account_id","type":"uuid","description":"FK to customers.account_id","required":true},{"name":"name","type":"text","description":"Project name","required":true},{"name":"name_ar","type":"text","description":"Project name (Arabic)","required":false},{"name":"code","type":"text","description":"Auto-generated code (SAL.NNNN_NNN). Read-only.","required":false},{"name":"project_type","type":"text","description":"residential, commercial, industrial, infrastructure, government","required":false,"enum_values":["residential","commercial","industrial","infrastructure","government"]},{"name":"project_size","type":"text","description":"small, medium, large, mega","required":false,"enum_values":["small","medium","large","mega"]},{"name":"current_phase","type":"text","description":"design, tender, foundation, structure, finishing, handover","required":false,"enum_values":["design","tender","foundation","structure","finishing","handover"]},{"name":"location_id","type":"uuid","description":"FK to locations","required":false},{"name":"poc","type":"uuid","description":"FK to contacts - project POC","required":false}]'::jsonb,
  '[{"target_table":"accounts","join_key":"customer_account_id=id","cardinality":"many-to-one","description":"Parent customer account"},{"target_table":"opportunities","join_key":"project_id","cardinality":"one-to-many","description":"Opportunities under this project"},{"target_table":"locations","join_key":"id=location_id","cardinality":"many-to-one","description":"Project location with zone"}]'::jsonb,
  '["Filter by customer_account_id to get all projects for a customer","Location zone_code is critical for delivery pricing"]'::jsonb
),
('opportunities', 'sales', 'Sales opportunities. Linked to a project and customer. Follows stage lifecycle: discovery → rfp → negotiation → won/lost.', 'الفرص البيعية',
  '[{"name":"id","type":"uuid","description":"Primary key","required":false},{"name":"customer_account_id","type":"uuid","description":"FK to customers.account_id","required":true},{"name":"project_id","type":"uuid","description":"FK to projects","required":true},{"name":"title","type":"text","description":"Opportunity title","required":true},{"name":"code","type":"text","description":"Auto-generated code (SAL.NNNN_NNN_NNN). Read-only.","required":false},{"name":"stage","type":"text","description":"Pipeline stage","required":false,"enum_values":["discovery","rfp","negotiation","won","lost"]},{"name":"status","type":"text","description":"active or closed","required":false,"enum_values":["active","closed"]},{"name":"interest_level","type":"text","description":"Customer interest level","required":false,"enum_values":["Very interested","Interested","Medium","Low interest","Not interested"]},{"name":"priority","type":"text","description":"Priority level","required":false,"enum_values":["low","medium","high","urgent"]},{"name":"expected_close_date","type":"date","description":"Expected order date","required":false},{"name":"source","type":"text","description":"Lead source","required":false},{"name":"contact_id","type":"uuid","description":"FK to contacts - opportunity contact","required":false},{"name":"assigned_to","type":"uuid","description":"FK to profiles - assigned salesperson","required":false},{"name":"lost_reason","type":"text","description":"Required when marking as lost","required":false},{"name":"won_at","type":"timestamptz","description":"Timestamp when won","required":false},{"name":"lost_at","type":"timestamptz","description":"Timestamp when lost","required":false},{"name":"materials_interest","type":"jsonb","description":"Material categories of interest","required":false}]'::jsonb,
  '[{"target_table":"projects","join_key":"project_id","cardinality":"many-to-one","description":"Parent project"},{"target_table":"accounts","join_key":"customer_account_id","cardinality":"many-to-one","description":"Customer account"},{"target_table":"quotations","join_key":"opportunity_id","cardinality":"one-to-many","description":"Quotations for this opportunity"},{"target_table":"communications","join_key":"opportunity_id","cardinality":"one-to-many","description":"Communication log"},{"target_table":"tasks","join_key":"opportunity_id","cardinality":"one-to-many","description":"Follow-up tasks"}]'::jsonb,
  '["Filter by stage for pipeline analysis","Filter by status=active AND deleted_at IS NULL for live opportunities","Join with accounts for customer name","won_at/lost_at timestamps indicate terminal states"]'::jsonb
),
('communications', 'sales', 'Activity log for all interactions. Every update creates a communication record as audit trail.', 'سجل التواصل والتفاعلات',
  '[{"name":"id","type":"uuid","description":"Primary key","required":false},{"name":"account_id","type":"uuid","description":"FK to accounts","required":false},{"name":"project_id","type":"uuid","description":"FK to projects","required":false},{"name":"opportunity_id","type":"uuid","description":"FK to opportunities","required":false},{"name":"contact_id","type":"uuid","description":"FK to contacts","required":false},{"name":"channel","type":"text","description":"Communication channel","required":true,"enum_values":["whatsapp","phone","email","meeting","site_visit","internal"]},{"name":"summary","type":"text","description":"What happened / note content","required":true},{"name":"direction","type":"text","description":"inbound or outbound","required":false,"enum_values":["inbound","outbound"]},{"name":"occurred_at","type":"timestamptz","description":"When it happened","required":false},{"name":"sentiment","type":"text","description":"positive, neutral, negative","required":false,"enum_values":["positive","neutral","negative"]},{"name":"outcome","type":"text","description":"Result of the interaction","required":false}]'::jsonb,
  '[{"target_table":"accounts","join_key":"account_id","cardinality":"many-to-one","description":"Customer account"},{"target_table":"opportunities","join_key":"opportunity_id","cardinality":"many-to-one","description":"Related opportunity"},{"target_table":"tasks","join_key":"communication_id","cardinality":"one-to-many","description":"Tasks created from this communication"}]'::jsonb,
  '["Filter by account_id for customer timeline","Filter by opportunity_id for opportunity timeline","channel=internal means internal note, not external communication","Order by occurred_at DESC for chronological feed"]'::jsonb
),
('tasks', 'sales', 'Follow-up tasks and action items. Created automatically by the GlobalActivity system. Auto-completed when a new update is logged.', 'المهام والمتابعات',
  '[{"name":"id","type":"uuid","description":"Primary key","required":false},{"name":"customer_account_id","type":"uuid","description":"FK to customers.account_id","required":false},{"name":"project_id","type":"uuid","description":"FK to projects","required":false},{"name":"opportunity_id","type":"uuid","description":"FK to opportunities","required":false},{"name":"communication_id","type":"uuid","description":"FK to communications - the update that created this task","required":false},{"name":"title","type":"text","description":"Task title","required":true},{"name":"task_type","type":"text","description":"Type of task","required":false,"enum_values":["follow_up"]},{"name":"status","type":"text","description":"Task status","required":false,"enum_values":["open","in_progress","done"]},{"name":"priority","type":"text","description":"Task priority","required":false,"enum_values":["low","medium","high","urgent"]},{"name":"channel","type":"text","description":"Preferred channel for follow-up","required":false},{"name":"due_at","type":"timestamptz","description":"Due date","required":false},{"name":"completed_at","type":"timestamptz","description":"When completed","required":false},{"name":"assigned_to","type":"uuid","description":"FK to profiles","required":false},{"name":"outcome","type":"text","description":"What happened when task was completed","required":false}]'::jsonb,
  '[{"target_table":"opportunities","join_key":"opportunity_id","cardinality":"many-to-one","description":"Related opportunity"},{"target_table":"communications","join_key":"communication_id","cardinality":"many-to-one","description":"Communication that created this task"}]'::jsonb,
  '["Filter by status=open for pending tasks","Filter by due_at <= now() for overdue tasks","Tasks are auto-completed when a new update is logged for the same opportunity"]'::jsonb
),
('quotations', 'sales', 'Price quotations linked to opportunities. Can be draft or sent. Stage transitions depend on quotation status.', 'عروض الأسعار',
  '[{"name":"id","type":"uuid","description":"Primary key","required":false},{"name":"opportunity_id","type":"uuid","description":"FK to opportunities","required":false},{"name":"customer_account_id","type":"uuid","description":"FK to customers.account_id","required":true},{"name":"project_id","type":"uuid","description":"FK to projects","required":false},{"name":"status","type":"text","description":"Quotation status","required":false,"enum_values":["draft","sent","accepted","rejected","expired"]},{"name":"is_soft","type":"boolean","description":"true=soft/unofficial quote, false=official quote","required":false},{"name":"quote_type","type":"text","description":"order or supply","required":false,"enum_values":["order","supply"]},{"name":"version","type":"integer","description":"Quotation version number","required":false},{"name":"subtotal","type":"numeric","description":"Sum of line items","required":false},{"name":"delivery_total","type":"numeric","description":"Sum of delivery costs","required":false},{"name":"total","type":"numeric","description":"Grand total","required":false},{"name":"currency","type":"text","description":"Always SAR","required":false},{"name":"valid_until","type":"date","description":"Quotation expiry date","required":false},{"name":"sent_at","type":"timestamptz","description":"When quotation was sent","required":false},{"name":"accepted_at","type":"timestamptz","description":"When quotation was accepted","required":false},{"name":"est_delivery_date","type":"date","description":"Estimated delivery date","required":false}]'::jsonb,
  '[{"target_table":"opportunities","join_key":"opportunity_id","cardinality":"many-to-one","description":"Parent opportunity"},{"target_table":"quotation_items","join_key":"quotation_id","cardinality":"one-to-many","description":"Line items"}]'::jsonb,
  '["Filter by status=draft for active drafts","sent_at IS NOT NULL means quote was officially sent","is_soft=false for official quotations that gate stage transitions"]'::jsonb
),
('quotation_items', 'sales', 'Line items in a quotation. Each item references a material and optionally a supplier.', 'بنود عرض السعر',
  '[{"name":"id","type":"uuid","description":"Primary key","required":false},{"name":"quotation_id","type":"uuid","description":"FK to quotations","required":true},{"name":"material_id","type":"uuid","description":"FK to materials","required":true},{"name":"supplier_material_id","type":"uuid","description":"FK to supplier_materials for pricing","required":false},{"name":"supplier_account_id","type":"uuid","description":"FK to suppliers.account_id","required":false},{"name":"quantity","type":"numeric","description":"Quantity ordered","required":false},{"name":"uom","type":"text","description":"Unit of measure","required":false},{"name":"unit_price","type":"numeric","description":"Price per unit in SAR","required":false},{"name":"delivery_price","type":"numeric","description":"Delivery cost per unit","required":false},{"name":"line_total","type":"numeric","description":"quantity * unit_price","required":false},{"name":"position","type":"integer","description":"Display order","required":false},{"name":"status","type":"text","description":"active or removed","required":false,"enum_values":["active","removed"]},{"name":"removed_at","type":"timestamptz","description":"Soft-delete timestamp","required":false}]'::jsonb,
  '[{"target_table":"quotations","join_key":"quotation_id","cardinality":"many-to-one","description":"Parent quotation"},{"target_table":"materials","join_key":"material_id","cardinality":"many-to-one","description":"Material being quoted"}]'::jsonb,
  '["Filter by status=active AND removed_at IS NULL for active items","Join with materials for material name and specs"]'::jsonb
),
('locations', 'sales', 'Physical locations for accounts and projects. Contains coordinates, city, region, and zone for delivery pricing.', 'المواقع الجغرافية',
  '[{"name":"id","type":"uuid","description":"Primary key","required":false},{"name":"region_code","type":"text","description":"Region code (e.g. RYD, MKH)","required":true},{"name":"zone_code","type":"text","description":"Delivery zone code for pricing","required":false},{"name":"city","type":"text","description":"Saudi city enum","required":false},{"name":"country","type":"text","description":"GCC country code, default SA","required":false},{"name":"lat","type":"numeric","description":"Latitude","required":false},{"name":"lng","type":"numeric","description":"Longitude","required":false},{"name":"address_text","type":"text","description":"Human-readable address","required":false},{"name":"address_link","type":"text","description":"Google Maps link","required":false},{"name":"place_name","type":"text","description":"Place/building name","required":false}]'::jsonb,
  '[{"target_table":"accounts","join_key":"id=location_id","cardinality":"one-to-many","description":"Accounts at this location"},{"target_table":"projects","join_key":"id=location_id","cardinality":"one-to-many","description":"Projects at this location"}]'::jsonb,
  '["zone_code is critical for delivery rate calculations","Join with regions and zones tables for zone names"]'::jsonb
);

-- 3. Update check constraint to allow 'archived'
ALTER TABLE public.agent_actions DROP CONSTRAINT agent_actions_status_check;
ALTER TABLE public.agent_actions ADD CONSTRAINT agent_actions_status_check CHECK (status = ANY (ARRAY['active','coming_soon','disabled','archived']));

-- 4. Archive all existing agent_actions
UPDATE public.agent_actions SET status = 'archived';

-- 5. Allow admins to manage agent_actions
CREATE POLICY "Admins can manage agent_actions"
  ON public.agent_actions FOR ALL TO authenticated
  USING (has_role(auth.uid(), 'admin'::app_role))
  WITH CHECK (has_role(auth.uid(), 'admin'::app_role));

-- 6. Insert 7 core sales intents
INSERT INTO public.agent_actions (intent_key, title_en, title_ar, status, tool_name, tables, menu_order, keywords, main_fields, example_phrases_en, example_phrases_ar) VALUES
('add_customer_v2', 'Add Customer', 'إضافة عميل', 'active', 'agent-write', ARRAY['accounts','contacts','customers','locations'], 1,
  ARRAY['add customer','new customer','عميل جديد','شركة جديدة'],
  '{"sections":{"customer":{"mode":"create","required":true},"project":{"mode":"create","required":false},"opportunity":{"mode":"create","required":false},"context":{"required":true},"next_action":{"required":true}},"required_questions":[{"key":"customer_name","path":"customer.displayName","q_en":"Company name?","q_ar":"اسم الشركة؟"},{"key":"poc_name","path":"customer.contactName","q_en":"Point of contact name?","q_ar":"اسم المسؤول؟"},{"key":"poc_phone","path":"customer.contactPhone","q_en":"Phone number?","q_ar":"رقم الجوال؟"},{"key":"context_summary","path":"context.summary","q_en":"Any notes about this customer?","q_ar":"ملاحظات عن العميل؟"},{"key":"next_action_type","path":"actions[0].taskType","q_en":"What is the next step?","q_ar":"الخطوة القادمة؟"},{"key":"next_action_due","path":"actions[0].dueDate","q_en":"When should we follow up?","q_ar":"متى المتابعة؟"}],"optional_prompts":[{"key":"project","q_en":"Want to add a project too?","q_ar":"تبي تضيف مشروع؟"},{"key":"opportunity","q_en":"Want to create an opportunity?","q_ar":"تبي تضيف فرصة؟"}],"auto_resolve":[]}'::jsonb,
  ARRAY['Add a new customer','Register new company','I have a new lead'],
  ARRAY['سجل عميل جديد','أضف شركة جديدة','عندي عميل جديد']
),
('add_project_v2', 'Add Project', 'إضافة مشروع', 'active', 'agent-write', ARRAY['accounts','projects','locations'], 2,
  ARRAY['add project','new project','مشروع جديد'],
  '{"sections":{"customer":{"mode":"select","required":true},"project":{"mode":"create","required":true},"opportunity":{"mode":"create","required":false},"context":{"required":true},"next_action":{"required":true}},"required_questions":[{"key":"customer_name","path":"customer.selectedId","q_en":"Which customer?","q_ar":"أي عميل؟"},{"key":"project_name","path":"project.name","q_en":"Project name?","q_ar":"اسم المشروع؟"},{"key":"project_type","path":"project.projectType","q_en":"Project type? (residential/commercial/industrial)","q_ar":"نوع المشروع؟"},{"key":"context_summary","path":"context.summary","q_en":"Any notes?","q_ar":"ملاحظات؟"},{"key":"next_action_type","path":"actions[0].taskType","q_en":"Next step?","q_ar":"الخطوة القادمة؟"},{"key":"next_action_due","path":"actions[0].dueDate","q_en":"When?","q_ar":"متى؟"}],"optional_prompts":[{"key":"opportunity","q_en":"Want to add an opportunity for this project?","q_ar":"تبي تضيف فرصة لهذا المشروع؟"}],"auto_resolve":["customer.selectedId from customer_name"]}'::jsonb,
  ARRAY['Add a project for a customer','Create new project','Register a new construction project'],
  ARRAY['أضف مشروع','سجل مشروع جديد','مشروع جديد لعميل']
),
('add_opportunity_v2', 'Add Opportunity', 'إضافة فرصة', 'active', 'agent-write', ARRAY['accounts','projects','opportunities','quotation_items'], 3,
  ARRAY['add opportunity','new opportunity','new deal','فرصة جديدة','صفقة'],
  '{"sections":{"customer":{"mode":"select","required":true},"project":{"mode":"select","required":true},"opportunity":{"mode":"create","required":true},"context":{"required":true},"next_action":{"required":true}},"required_questions":[{"key":"customer_name","path":"customer.selectedId","q_en":"Which customer?","q_ar":"أي عميل؟"},{"key":"project_name","path":"project.selectedId","q_en":"Which project?","q_ar":"أي مشروع؟"},{"key":"opp_title","path":"opportunity.title","q_en":"Opportunity title?","q_ar":"عنوان الفرصة؟"},{"key":"interest_level","path":"opportunity.interestLevel","q_en":"Interest level? (Very interested/Interested/Medium/Low interest)","q_ar":"مستوى الاهتمام؟"},{"key":"context_summary","path":"context.summary","q_en":"What happened?","q_ar":"ماذا حصل؟"},{"key":"next_action_type","path":"actions[0].taskType","q_en":"Next step?","q_ar":"الخطوة القادمة؟"},{"key":"next_action_due","path":"actions[0].dueDate","q_en":"When?","q_ar":"متى؟"}],"optional_prompts":[],"auto_resolve":["customer.selectedId from customer_name","project.selectedId from project_name"]}'::jsonb,
  ARRAY['Add a new opportunity','Create a deal','I have a new sales lead'],
  ARRAY['أضف فرصة جديدة','سجل صفقة','عندي فرصة بيع']
),
('log_update_v2', 'Log Update', 'تسجيل تحديث', 'active', 'agent-write', ARRAY['opportunities','communications','tasks'], 4,
  ARRAY['log update','add update','تحديث','متابعة','تسجيل تحديث'],
  '{"sections":{"customer":{"mode":"select","required":false},"project":{"mode":"select","required":false},"opportunity":{"mode":"select","required":true},"context":{"required":true},"next_action":{"required":true}},"required_questions":[{"key":"opp_ref","path":"opportunity.selectedId","q_en":"Which opportunity?","q_ar":"أي فرصة؟"},{"key":"context_summary","path":"context.summary","q_en":"What happened?","q_ar":"ماذا حصل؟"},{"key":"next_action_type","path":"actions[0].taskType","q_en":"What is next?","q_ar":"الخطوة القادمة؟"},{"key":"next_action_due","path":"actions[0].dueDate","q_en":"When?","q_ar":"متى؟"}],"optional_prompts":[],"auto_resolve":["customer.selectedId from opportunity","project.selectedId from opportunity"]}'::jsonb,
  ARRAY['Log an update','Add follow-up note','Record a customer interaction'],
  ARRAY['سجل تحديث','أضف ملاحظة متابعة','سجل تواصل مع عميل']
),
('mark_won_v2', 'Mark Won', 'تسجيل فوز', 'active', 'agent-write', ARRAY['opportunities','communications','tasks'], 5,
  ARRAY['mark won','won deal','فاز','كسبنا','ربحنا الصفقة'],
  '{"sections":{"customer":{"mode":"select","required":false},"project":{"mode":"select","required":false},"opportunity":{"mode":"select","required":true},"context":{"required":true,"auto_generate":"Opportunity marked as WON"},"next_action":{"required":true,"auto_generate":"Process order"}},"required_questions":[{"key":"opp_ref","path":"opportunity.selectedId","q_en":"Which opportunity?","q_ar":"أي فرصة؟"}],"optional_prompts":[],"auto_resolve":["customer.selectedId from opportunity","project.selectedId from opportunity"],"business_rules":["Opportunity must have a sent quotation (sent_at IS NOT NULL) to be marked won","Sets stage=won, status=closed, won_at=now()","Auto-closes all open tasks"]}'::jsonb,
  ARRAY['Mark this deal as won','We won the deal','Customer accepted the quote'],
  ARRAY['الفرصة ربحناها','العميل وافق','سجل فوز']
),
('mark_lost_v2', 'Mark Lost', 'تسجيل خسارة', 'active', 'agent-write', ARRAY['opportunities','communications','tasks'], 6,
  ARRAY['mark lost','lost deal','خسرنا','ضاعت الفرصة'],
  '{"sections":{"customer":{"mode":"select","required":false},"project":{"mode":"select","required":false},"opportunity":{"mode":"select","required":true},"context":{"required":true,"auto_generate":"Opportunity marked as LOST"},"next_action":{"required":false}},"required_questions":[{"key":"opp_ref","path":"opportunity.selectedId","q_en":"Which opportunity?","q_ar":"أي فرصة؟"},{"key":"lost_reason","path":"opportunity.lostReason","q_en":"Why was it lost?","q_ar":"ليش خسرناها؟"}],"optional_prompts":[],"auto_resolve":["customer.selectedId from opportunity","project.selectedId from opportunity"],"business_rules":["lost_reason is mandatory","Sets stage=lost, status=closed, lost_at=now()","Auto-closes all open tasks"]}'::jsonb,
  ARRAY['Mark this deal as lost','We lost the opportunity','Customer went with competitor'],
  ARRAY['خسرنا الفرصة','العميل راح لمنافس','سجل خسارة']
),
('schedule_task_v2', 'Schedule Task', 'جدولة مهمة', 'active', 'agent-write', ARRAY['tasks','communications'], 7,
  ARRAY['schedule task','reminder','follow up','ذكرني','مهمة','متابعة'],
  '{"sections":{"customer":{"mode":"select","required":false},"project":{"mode":"select","required":false},"opportunity":{"mode":"select","required":false},"context":{"required":true},"next_action":{"required":true}},"required_questions":[{"key":"context_summary","path":"context.summary","q_en":"What is this about?","q_ar":"عن ماذا؟"},{"key":"next_action_type","path":"actions[0].taskType","q_en":"What type of follow-up?","q_ar":"نوع المتابعة؟"},{"key":"next_action_due","path":"actions[0].dueDate","q_en":"When?","q_ar":"متى؟"}],"optional_prompts":[{"key":"opportunity","q_en":"Link to an opportunity?","q_ar":"تربطها بفرصة؟"}],"auto_resolve":[]}'::jsonb,
  ARRAY['Schedule a follow-up','Remind me to call','Set a task for next week'],
  ARRAY['ذكرني أتصل','جدول متابعة','حط مهمة الأسبوع القادم']
);
